### ISSUE TITLE
How to set max ITER for adjoint seperately?

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#1024]
Is there any way to set max ITER for adjoint solution separately during shape optimization? My direct solution takes a lot of iterations to converge but adjoint converges quickly. The adjoint solution also does not stop after the convergence criteria is satisfied. It appears that there is no convergence criteria set for adjoint set in the solver.

Thanks in advance.

**Comment by auzbaig** [comment]
The feature is available in v6. I am downgrading to it because of it and several other reasons. Closing the issue.

**Comment by pcarruscag** [comment]
Part of the reason I never gave much attention to the current optimization scripts, and instead developed my own, is that I need different settings for primal and adjoint and the optimization scripts cannot handle that.

I don't think we should have different config settings for primal and adjoint.

I'm certain the adjoint solver considers the convergence criteria, you probably did something wrong in your setup (I'm guessing the fields you are monitoring do not exist for the adjoint, hence it has nothing to use as convergence field) but since you did not attach your config file, all I can tell you is to read the documentation https://su2code.github.io/docs_v7/Solver-Setup/

> ... I am downgrading ...

Yes you are. Honestly I envy this kind of pragmatism, it is probably why SU2 has tens or hundreds of "feature branches" lagging behind master by several versions. I feel like ranting but I'll be pragmatic for once.

**Comment by auzbaig** [comment]
Thanks @pcarruscag for responding! I really appreciate you taking time to answer this.

Well, I was just looking at the density residuals for convergence. That should be valid for both primal and adjoint. I have attached my config file for future reference. The same works for v6 though.

Yes, downgrading hurts. But I had good reasons to do so because of the shape optimization scripts for turbomachinery are way more developed for v6 than v7. I wish I could have done that earlier. Plus the MPI issue as well #990. Now I am able to use 30 instead of 3 cores and that makes one hell of a difference.

The good part about git is that I can go back to v6.1.0 tag and get not only the code and Testcases but the website at that version as well. That certainly helps.
