### ISSUE TITLE
time-varying boundary conditions

### ISSUE THREAD

**Issue by flybob91** [su2code/SU2#1079]
Dear SU2 developers,
Is it possible to have a time-varying boundary condition? I would interested in the possibility to apply a time-varying velocity

Thank you for your job

Best regards

**Comment by clarkpede** [comment]
This is possible using the Python wrapper.  There are no tutorials for this yet, but you can check out PR #488, PR #503. PR #516.  There's currently a regression test using unsteady heat-transfer boundary conditions at: https://github.com/su2code/SU2/tree/master/TestCases/py_wrapper/flatPlate_unsteady_CHT . You can use that as an example.  Velocity BCs will be very similar.

**Comment by flybob91** [comment]
Thank you Clark,
I will come back as soon as I will be able to run the case to extend your script.

Best regards

**Comment by flybob91** [comment]
I met some problem in the original launch_unsteady_CHT_FlatPlate.py in [in the unsteady CHT flate plate] (https://github.com/su2code/SU2/tree/master/TestCases/py_wrapper/flatPlate_unsteady_CHT) case.

The first problem is that the function GetUnsteady_TimeStep() (line 141) returns an  object of class 'SwigPyObject' while the SU2Driver.GetTime_Iter() (line 142) returns a 'int' object. This causes the execution to fail since the two variable are multiplied at line 144. 

I tried to inset a numerical value for deltaT in order to avoid the problem but I got the following error
`TypeError: in method 'CDriver_SetVertexTemperature', argument 4 of type 'passivedouble'`

So I suppose the problem is the function  GetTime_Iter() which shouldn't return an 'int' object. Has anyone met the same problem?

**Comment by aleargix** [comment]
Hello SU2 developers,

I am reopening this topic because I am studying a case of jet impingement on a wall with a time-varying flow at the inlet. I have used compressible RANS and TOTAL_CONDITIONS as inlet BC. Specifically, I have set a time-varying stagnation pressure to achieve a time-varying flow.

To do this, I used the Python script mentioned in the previous messages, modifying some commands to suit my problem. I should mention that I do not use Python frequently, so there are likely some errors. Indeed, I checked the documentation and noticed that the command I used to vary the pressure at the inlet (SetMarkerCustomPtotal) is not listed.

However, when I run the simulation, it seems to work quite well. Unfortunately, when examining the pressure field, it appears that the time-varying boundary conditions are applied  on the walls with no-slip conditions (represented by the MARKER_ISOTHERMAL command) and not at the inlet as I want.

Could you please tell me what changes I need to make in the Python script to correctly set up the problem? For completeness, I am attaching the script I modified, the configuration file, and a video of the pressure field.

Thank you in advance for your help.

Best Regards.
[2D_jet_val_unsteady_5.zip](https://github.com/user-attachments/files/15524970/2D_jet_val_unsteady_5.zip)

**Comment by pcarruscag** [comment]
Seems like we lost that function recently, I'll try to fix it and put together a working example, then you can adapt it to your problem.

**Comment by aleargix** [comment]
Thanks a lot for your reply. I look forward to your future updates.

**Comment by pcarruscag** [comment]
I might rename some stuff before merging, but see if this helps with your case https://github.com/su2code/SU2/pull/2296

**Comment by aleargix** [comment]
Sorry to bother you again. I am trying to figure out how (from a practical point of view) implement your changes in my SU2 code. May I just add your three lines somewhere? In such case could you help me with the name of the file that I should edit? Thank you in advance for your support.

**Comment by bigfooted** [comment]
Hi, 
So I am assuming you are not so familiar with using git, so here is what you need to do.
If you follow the link [#2296](https://github.com/su2code/SU2/pull/2296/files) and go to the section 'files changed' you can see that it's quite a lot of changes. The changes are currently added (merged) to the 'develop' branch (when you follow the link you can see this message). So what you need to do is update your github repository. 
I assume that you already have a local copy of SU2 and that you obtained this from github using 
`git clone https://github.com/su2code/SU2.git`
You switch to the develop branch:
`git checkout develop`
you update your develop branch:
`git pull`
now you have all changes, and you need to recompile.
There is an example in TestCases/py_wrapper/custom_inlet that you could use.
For completeness, here is a link to the docs: https://su2code.github.io/docs_v7/home/
