### ISSUE TITLE
Issue with Periodic Boundary Conditions

### ISSUE THREAD

**Issue by GomerOfDoom** [su2code/SU2#1090]
**Describe the bug**
There is some issue with having two sets of intersecting periodic boundary conditions.

I was attempting to simulate plane channel flow (Poiseuille) between two infinite plates with SU2 v. 7.0.7 using RANS, but the results are not correct. Specifically, I see a lot of garbage in the corners, where the periodic BCs intersect (see pictures).

![corner_problems](https://user-images.githubusercontent.com/6933834/95637061-a5771c80-0a45-11eb-80d9-9e81affa0c89.png)

I thought that periodic BCs had been updated and working, and that having multiple periodic BCs was not an issue. Is this not the case, or have I done something wrong?

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*
(See attached)

**Desktop (please complete the following information):**
 - OS: Arch Linux - Linux Kernel 5.8.14
 - C++ compiler and version: GCC 10.2.0
 - MPI implementation and version: Open MPI 4.0.5
 - SU2 Version: 7.0.7 - branch: develop - commit: e9c824cd70

[channel_bug_files.tar.gz](https://github.com/su2code/SU2/files/5357906/channel_bug_files.tar.gz)

**Comment by clarkpede** [comment]
Are these effects present in the converged solutions? Or only the transient steps?

**Comment by GomerOfDoom** [comment]
An update...

I've run a few other cases and noticed something else. It turns out that option NUM_METHOD_GRAD_RECON has a significant impact on the channel flow with periodic boundaries.

![xz_roe_comp](https://user-images.githubusercontent.com/6933834/98713194-245cbf00-233c-11eb-9f9e-94f4b301a626.png)

1) In this picture, the streamwise and​ spanwise boundaries are periodic.
- The top two images in this picture are from a run without NUM_METHOD_GRAD_RECON. As you can see, there is a lot of garbage in the corners, and the simulation does not converge well.
- The bottom two images are from a run with NUM_METHOD_GRAD_RECON set to LEAST_SQUARES.
- Note that in both cases, NUM_METHOD_GRAD is set to GREEN_GAUSS

![x_roe_comp](https://user-images.githubusercontent.com/6933834/98713350-5cfc9880-233c-11eb-83f2-89c3d9889739.png)

2) In this picture, only the streamwise boundaries are periodic, while the spanwise boundaries are symmetry.
- Again, the top to images in this picture are from a run without NUM_METHOD_GRAD_RECON. This time, there is no real issue in the corners, but there is some weirdness on the top and bottom boundaries (although, the perturbations are small).
- The bottom two images are from a run with NUM_METHOD_GRAD_RECON set to LEAST_SQUARES.

It looks like an entry for NUM_METHOD_GRAD_RECON was *just* added to the config_template.cfg (there was not one there, previously), but I'm wondering if the behavior in the periodic boundary corners is expected if the gradient reconstruction option is not used, or does that indicate something wrong there? I'm not sure I understand why the periodic boundaries would pose an issue for the scheme without the gradient reconstruction. 

As far as I can tell, this issue is separate from that mentioned by @clarkpede, but these meshes are small and I've only run on up to 16 MPI ranks.

**Comment by pcarruscag** [comment]
What about using weighted least squares for NUM_METHOD_GRAD? (if you don't specify something for NUM_METHOD_GRAD_RECON the method from NUM_METHOD_GRAD is used).

Context: Plain least squares will under-predict gradients in stretched meshes whereas GG and WLS are not supposed to.

**Comment by economon** [comment]
Here's my best guess at what is happening: we are not correctly identifying the complete set of neighbors along intersections of two or more periodic boundaries (maybe duplicates, or maybe missing some neighbors). Without the correct stencil, GG will be incorrect due to integrating over the wrong control volume (repeated faces or missing faces). It also needs the correct volume for division in the GG evaluation.

LSQ gets away with it most likely because the stencil can be defined independently of the actual set of neighbors (doesn't need to be a closed control volume) - if you miss a neighbor or duplicate a neighbor, you should end up with a similar answer. WLSQ may also get away with it, but with the weighting by inverse distance of the neighbor, you could still see some artifacts in the solution with missing/duplicate neighbors.

If you have some time, can you take a look at the periodic matching routines and periodic communication preprocessing? The routines are sort of nasty, since the identification is not so straightforward in a vertex-based code with the DoFs on the boundary, but I expect we are missing something there still with intersecting periodic boundaries.

**Comment by pcarruscag** [comment]
So... I was looking at the gradient reconstruction option ([because of an unrelated problem I introduced](https://www.cfd-online.com/Forums/su2/234885-7-1-1-crashing-central-schemes.html)) and it seems we do not have periodic communications for them.
This does not explain the problem, but I guess it is something else to have in mind.
