### ISSUE TITLE
Bug in SURFACE_TECPLOT for SU2 v7.0.7 onwards

### ISSUE THREAD

**Issue by irahulsonkar** [su2code/SU2#1182]
It seems some **bug** is there in **SU2 v7.0.7** onward when writing **surface file** in .szplt format. 
For SU2 v7.0.6 and below version, surface szplt file opens smoothly in Tecplot 2020 running on Ubuntu 20.04 but for later version it crashes unexpectedly for the same case (same .cfg and .su2) though flow szplt file seems to be working fine.

**Comment by vdweide** [comment]
Would it be possible to provide us the .cfg and .su2 files?

**Comment by irahulsonkar** [comment]
It can be checked with SU2 Quick Start Test case NACA 0012 airfoil. 
Paraview (.vtu) output for flow and surface is perfectly fine but Tecplot (.szplt) create erroneous data in 3rd dimension for this 2D case.

**Comment by vdweide** [comment]
That's weird. I could open the surface szplt file without a problem. I am running Tecplot 2020 on Ubuntu 20.04 as well. I did use the develop version of SU2 though. Could you try the develop version to see if that works for you?

BTW, if needed, you can also open the paraview vtu file in Tecplot.

**Comment by irahulsonkar** [comment]
Please have a look at attached images of surface_flow.szplt. In XY view it looks fine but when you rotate it you can see the problem.

![surface_flow_NACA0012](https://user-images.githubusercontent.com/59632055/106539582-9d397480-6541-11eb-8c8e-f6b586c2b1c1.png)

![surface_flow_NACA0012_rotated](https://user-images.githubusercontent.com/59632055/106539589-a1659200-6541-11eb-872e-6b3111ab5aa4.png)

**Comment by vdweide** [comment]
The answer to that is very simple. Look in the data set that is present in the szplt file. The z-coordinate is not in there anymore and consequently Tecplot takes the next variable, the density in this case, as the z-coordinate. Consequently you git a picture like you showed. The same is true for the field solution. Also there the z-coordinate is not present in the szplt file and hence you get a rather funny picture when you attempt to visualize this in 3D. But 2D visualization works just fine.

In contrast the z-coordinate is stored in the vtu files, because the standard requires that. Hence you can still visualize this in 3D.

Could you try a truly 3D test case to see if that visualizes fine? If so, please let us know such that we can close this issue.

**Comment by irahulsonkar** [comment]
Thanks for your comments. I checked for a 3D test case (OneraM6) and it works fine.
It seems to be giving error only for one of my particular case where v7.0.6 work but not later version for SURFACE_TECPLOT.
