### ISSUE TITLE
SU2 installation: ninja subcommand fails because of linking target errors on HPC cluster

### ISSUE THREAD

**Issue by susmitsj** [su2code/SU2#1278]
I am attempting to install SU2 master branch and/or feature_NEMO branch on a HPC cluster (https://arc.vt.edu/tinkercliffs/). The modules that I am loading prior to installation are listed below:
GCC/10.2.0
OpenMPI/4.0.5-GCC-10.2.0
CMake/3.18.4-GCCcore-10.2.0
Ninja/1.10.1-GCCcore-10.2.0
Python/3.8.6-GCCcore-10.2.0

My meson command is:
./meson.py build -Denable-autodiff=true -Denable-directdiff=true -Denable-mpp=true

The ninja subcommand fails because it fails to link various targets (SU2_GEO/src/SU2_GEO, SU2_DOT/src/SU2_DOT, SU2_DEF/src/SU2_DEF, SU2_SOL/src/SU2_SOL, SU2_CFD/src/SU2_CFD) and then proceeds to Linking static target SU2_CFD/src/libSU2core_AD.a where the message appears: 'ninja: build stopped: subcommand failed.'

The reason for failing to link the targets is common in all instances and is shown as '/apps/easybuild/software/tinkercliffs-rome/libevent/2.1.12-GCCcore-10.2.0/lib64: pread failed: Is a directory'.

Please let me know if there's a way to get around this issue. 

Thanks in advance.

**Desktop (please complete the following information):**
 - OS: Linux
 - C++ compiler and version: GCC 10.2.0
 - MPI implementation and version: OpenMPI 4.0.5
 - SU2 Version: 7.1.1

**Comment by pcarruscag** [comment]
Contact the team that supports the cluster, they are usually much more knowledgeable about that type of problem.
90% of the times I had similar problems was because I was not using the programming environment properly.
One common issue is that clusters that are properly setup use compiler wrappers, which you should use instead of trying to use gcc directly.

We have absolutely no way no replicate this issue, hence I'm closing it.
