### ISSUE TITLE
Poor decomposition

### ISSUE THREAD

**Issue by BTemp1282020** [su2code/SU2#1307]
Description:
With our current mesh, on an 8 node, 32 intel cores per node system, our average CPU utilization per node ranges between 31% and 86%.  The interconnect fabric is far from fully utilized in terms of throughput.  Memory utilization is not nearly that inconsistent (differences of 2-3x).

On a different system, 4 node 128 AMD cores per node, the average CPU utilization per node ranges between 54% and 95%.  The same mesh is used in both instances.

To Reproduce:
Run a mesh on a multi-node system with different core counts and I expect that you will see varied CPU utilization per node depending on how ParMETIS decided to partition the mesh

System Software Environment:
OS: CentOS7
GCC 7.3.1
MPI: openMPI 3.1.2
SU2 7.0.1 (with modifications so that it can write files and to correct the fixed CL issue)

Do you have recommendations on how to improve the decomposition?
Or, if parmetis does not give sufficient options to improve the decomposition result, perhaps change this to a feature request to add ptscotch and/or zoltan support?

**Comment by pcarruscag** [comment]
Update to the current version of SU2 please, we updated the Metis partitioning strategy here: https://github.com/su2code/SU2/pull/1059

**Comment by pcarruscag** [comment]
If you would like to add Scotch to SU2 I can point you to the right places in the code. I played around with it for some meshes and the advantage did not look massive. On some systems we get a good speed-up from the hybrid parallel implementation ~20% though.

**Comment by BTemp1282020** [comment]
Oops, there was a typo: the SU2 version is actually 7.1.0 not 7.0.1

I'm glad you had looked into it.  On high DOF counts per partition, I know they tend to be fairly similar.  I only see big differences on meshes with 20M DOF on >200 partitions (i.e. where accounting for partition connectivity is more important).  While having the option for different partitioners would be a nice feature, I do not know if the SU2 user-base would actually have much interest in it.

The last time we tried a hybrid parallel approach our performance improvement was quite low (<10%).

Thank you for your input.

**Comment by pcarruscag** [comment]
Ah! Ok, so you may try to tweek PARMETIS_POINT_WEIGHT and PARMETIS_EDGE_WEIGHT.
To balance edges perfectly the  point weight may have to be set to a negative value. Those values must be integers.

With certain features it is important to have good defaults because a lot of users will not be aware of all the details. So if scotch proves to be much better for large problems, we can create interest.

The cost model we use for partitioning is limited, it does not account for boundaries or for multigrid. If you have large symmetry planes this might create imbalance.
The hybrid implementation in SU2 reduces the number of partitions created, which might help parmetis in your case.

**Comment by BTemp1282020** [comment]
Ooh, that sounds like exactly what I'm looking for.  Do I set those as environment variables or in a different manner?

I'll have to check the hybrid again to see how it does.

Thanks!

**Comment by pcarruscag** [comment]
They are SU2 config options. I think they are explained in the config_template in more detail (98% sure).

**Comment by BTemp1282020** [comment]
Ah, it is there!  Many thanks
