### ISSUE TITLE
Writing solution data in steady state cases without overwriting them

### ISSUE THREAD

**Issue by thunderbird-98** [su2code/SU2#1463]
I am running an FSI steady-state case with CFD and FEA coupled. I want to write every outer iteration without the file getting overwritten.

"OUTPUT_WRT_FREQ" is overwriting the output files

**Comment by pcarruscag** [comment]
Hi, we don't have an option to "keep all files", the intended behaviour in steady state is to have only the last solution.
You could emulate what you want via the python wrapper by running some steps and them saving the files manually.

**Comment by bigfooted** [comment]
We have introduced something like this in one of the feature branches (feature_flamelet).
We have introduced an additional keyword WRT_SOL_OVERWRITE= NO
Instead of overwriting the restart and paraview files, it will append the iteration number to the filename each time it writes the files. Is this what you need? 

Maybe we can accelerate this and put it into develop independent of this feature branch.

**Comment by thunderbird-98** [comment]
Yes that's exactly what I need. Thanks for your help

**Comment by pcarruscag** [comment]
Will be available in the next release thanks to @bigfooted
