### ISSUE TITLE
HISTORY_OUTPUT only accepts groups, not fields

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#1493]
**Describe the bug**

Maybe "it's not a bug, it's a feature", but:
I can for example select a field for output
SCREEN_OUTPUT= INNER_ITER 
or use the group,
SCREEN_OUTPUT= ITER
which is equivalent to choosing the fields INNER_ITER, OUTER_ITER, TIME_ITER

But for HISTORY_OUTPUT, I can only choose the group. This leads to a lot of data in the history file if I want to know what happens at a number of markers. So I would like to do this:

HISTORY_OUTPUT= (INNER_ITER, SURFACE_MASSFLOW)

to get 2 columns in my history file. Instead I have to do this:

HISTORY_OUTPUT= (ITER, SURFACE_MASSFLOW)

which leads to a lot of columns. Is there a reason that only groups are allowed or can this limitation be lifted safely?

**Comment by pcarruscag** [comment]
In some parts of the code it looks like the intention was to allow both modes, see
COutput::SetHistoryFile_Header `if (requestedField == field.outputGroup || (requestedField == fieldIdentifier)){`

In principle you "just" need to apply that logic to every use of `requestedHistoryFields`.

If would be more difficult to make the screen output know about groups, because it uses the names you give to lookup values directly, whereas the history loops over all available values and checks their group against all groups you give it.

**Comment by bigfooted** [comment]
Thanks! Yeah I noticed that in COutput::CheckHistoryOutput, there is some preliminary check to filter out invalid keywords, where for history the group keywords are checked.  I will then look into making history accept fields. Not sure how useful an extension of screen output will be to accept groups.
