### ISSUE TITLE
Test cases throwing invalid option name error

### ISSUE THREAD

**Issue by gforsyth** [su2code/SU2#152]
Just compiled today and it seems like the options `CFL_ADAPT` and `CFL_ADAPT_PARAM` have been deprecated?  

Running the 2D inviscid cylinder and the euler channel flow example both throw an error

```
CFL_ADAPT: invalid option name. Check current SU2 options in config_template.cfg.
CFL_ADAPT_PARAM: invalid option name. Check current SU2 options in config_template.cfg.
```

Commenting these lines out lets the test cases run but I'm not sure what the default behavior is (are these running with adaptive CFL if we don't pass that parameter at all?)

**Comment by fpalacios** [comment]
Hi,

We have just updated (30min ago) the master branch of the SU2 and TestCases repositories. Could you please try again?

If you are using the develop branch, please remember that you should use the develop branch for the SU2 and TestCases repositories. Otherwise the options don’t match.

Pleas let us know if it is working for you now.

Best,
Francisco

**Comment by gforsyth** [comment]
Just finished compiling.  Test cases are fine now.  I had an up-to-date Test Cases repo but my SU2 repo was behind by a commit.  Sorry for the false alarm!

**Comment by labarba** [comment]
We are actually having a group meeting, cloned and compiled in two machines while discussing SU2 with the whole group, and experienced this one-commit-behind issue. This has all been in the context of brainstorming open-science and reproducibility practices for CFD. 

We've continued to discuss it and we wonder if this might be avoided by keeping the Tests as a folder in the main SU2 repo, rather than having a separate repo for Tests. 

Is there a reason why you decided to have a separate repository for Tests?

**Comment by btracey** [comment]
Github has a size restriction on repository size (in MB)

**Comment by labarba** [comment]
And why is your Test repo so large?
Perhaps some data files would be happier living elsewhere?

I'm thinking that if your Tests load large mesh files, for example, these mesh files could be placed in a data repository (like Figshare, Data Dryad, Zenodo), and your configuration files for each test could fetch the data it needs. I would imagine that the input data does not change often (or perhaps ever?) and one permalink and DOI is better suited for data than a version-controlled repo.

**Comment by fpalacios** [comment]
Hi Lorena,

Sorry for the delay getting back to you. You are right, and the TestCases repository is starting to be huge, mainly because of the stuff that GitHub generates to track the files.

Easy to maintain/access alternatives are very welcome. Some releases ago, the grids were in another place (or lab server) and in Github we only had the config files, unfortunately we checked that for some users it was frustrating to download the config files and then go to another place to download the grids. From our practical point of view, the current setting is ideal to run the regression tests. But we are open to any change that benefits the SU2 users/developers community. 

Now, it is very easy to download and modify the TestCases (keep in mind that the options in the config files change frequently) but, the price to pay is a large GitHub repository that it is difficult to download if you don’t have a good internet connection.

Anyway, I think you are coming to Stanford in one week, it would be great to chat with you. We would love to have you and your group as a SU2 developer/user.

Looking forward to meeting you and thanks for testing SU2.

Best
Francisco


--
Dr. Francisco Palacios
Engineering Research Associate at Stanford University
AIAA Senior Member, SIAM Member, and SU2 lead developer
Editorial Board Member for Scientific Report (Nature Publishing Group)
Intel Parallel Computing Center

Personal webpage: http://adl.stanford.edu/people/fpalacios.html
SU2 webpage: http://su2.stanford.edu/

Department of Aeronautics and Astronautics
Durand Building. Room 357
Stanford University
Stanford CA 94305
United States
