### ISSUE TITLE
SU2_DOT giving wrong results

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#179]
SU2_DOT seems to give wrong results. For example using the test case cont_adj_euler/naca0012.
Just use the continuous_adjoint.py script to test this.

**Comment by hlkline** [comment]
Thank you for your interest in SU2.
Could you please elaborate on what you are comparing the gradients to which leads to this conclusion?

**Comment by talbring** [comment]
If I am not doing something stupid here, it is very obvious. However, also Finite Differences and Complex step method tell me that there is something wrong.
![grad_naca](https://cloud.githubusercontent.com/assets/4933860/7705547/2ffdcfce-fe45-11e4-8267-8fecd7c9f6d4.png)

**Comment by hlkline** [comment]
I was not able to reproduce this behavior. Below is the result I get when using the master branch for both the code and the test cases. 

![image](https://cloud.githubusercontent.com/assets/5167760/7709282/d36254b2-fe10-11e4-8827-f01ec46fbf0f.png)

Note that since the config file provided uses a restart it depends on also having the provided restart files, which may have been produced with slightly different settings (ie, lower CFL number), and if you are not using the restart files you should check that the solution has converged. If you have further questions about the settings of SU2, checking convergence, etc please post them to the forum at:
cfd-online.com/Forums/su2/

You will find that in addition to a wider audience who can answer your questions, the answers may also already be posted from users who had similar problems.

**Comment by talbring** [comment]
I figured out that it happens only if you compile the code without MPI support. Otherwise it will be fine.

**Comment by hlkline** [comment]
This is exactly the sort of problem that the forum is ideal for:
http://www.cfd-online.com/Forums/su2-installation/150297-errors-when-attempt-run-parallel-computation.html

Please direct further such problems to the forum.

**Comment by hlkline** [comment]
Sorry, I misread your comment and thought it might be a problem with compiling with MPI. We are checking the serial version now.

**Comment by economon** [comment]
Verified. We're looking into the issue...

**Comment by talbring** [comment]
Ok I think I have figured out the problem. Apparently the local index of a node and its global index do not coincide if compiled without MPI. So for example if you do 
iPoint = geometry->vertex[iMarker][iVertex]->GetNode() 
and then
 Global_Index = geometry->node[iPoint]->GetGlobalIndex() 
we have iPoint != Global_Index.

I just fixed it by writing the global index in the surface sensitivity file (now it is consistent with the surface flow file).
