### ISSUE TITLE
Species Information not transmitted across interfaces

### ISSUE THREAD

**Issue by DoctorRobertT** [su2code/SU2#1818]
**Describe the bug**
When using species transport in a problem using the fluid-fluid interface there is no information on species being transmitted across the interface. In addition if you use the MARKER_ANALYZE in the cfg file the code bombs on startup as follows:

Error in "virtual void CMultizoneOutput::SetMultizoneHistoryOutputFields( const COutput* const*, const CConfig* const*)":
-------------------------------------------------------------------------
Per Surface output group unknown: SPECIES_COEFF_SURF
------------------------------ Error Exit ------------------------------

**Desktop (please complete the following information):**
 - Ubuntu 18.04.5 on WSLV2 on Windows 10
 -gcc version 7.5.0
 - Openmpi 2.1.1
 - SU2 Version: 7.4.0

[MZ.zip](https://github.com/su2code/SU2/files/9993823/MZ.zip)

**Comment by bigfooted** [comment]
Hi,

OK, there were actually 2 problems here. One is that the species mass fractions were not transported across the zone interface. The other is that for MARKER_ANALYZE, we did not add species information, but later in the code we assumed that it was present.

Both are now fixed in the feature branch, but it will be a while before it ends up in the master version. In the mean time, you could clone the SU2 git repository and then do a git checkout feature_species_multizone and compile the fixed branch yourself.
Thanks for spotting the problem!

**Comment by bigfooted** [comment]
@DoctorRobertT this is now merged in develop. Please check out the testcase in Testcases/species_transport/multizone and let us know of any other missing functionality. Thanks!
