### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GregVernon** [su2code/SU2#183]
Let me begin by saying "Thank you so, so much for your time and efforts to write SU2 and then distribute as open source!" 

I now wish to make a complaint -- as far as I can tell there is not even a command manual for SU2.  I think this should be a requirement for SU2.  Tutorials are not enough:

>   SU2 includes strict error checking of the config file upon execution of one of the C++ modules. For example, the code **will throw errors if unknown options are specified**, options appear more than once, extra text appears outside of comments, etc.

A user should be able to reference a single document to find command syntax and options.  As an excercise, I "tried" to use a dd-ilut preconditioner with 2 submatrices, symmetric overlap, a drop-tolerance of 1e-4, and a fill of 1.3, with a GMRES solver utilizing a modified Gram-Schmidt orthoganolization, kspace of 30, and RCM reordering... SU2 failed.

Ok, so I didn't *actually* try to do this, but if I were to try this how would I know SU2 *couldn't* use this?  To fill in this exercise I accessed the Trilinos Aztec User Manual: https://trilinos.org/oldsite/packages/aztecoo/AztecOOUserGuide.pdf which, while it doesn't attempt to tell me *what* a krylov subspace is, at least tells me that I can and how to use the argument *AZ_kspace*.  Then as a user I can google *GMRES kspace* to find the theory / explanation if I so choose.

Can this be a thing?  At least a text document with commands and allowed arguments?

**Comment by hlkline** [comment]
Config options and their options can be found in:
https://github.com/su2code/SU2/blob/master/config_template.cfg
As a part of the code repository, this document will remain up to date with whatever version of the code you have. I believe that this is the single document to which you refer. I apologize that its location or purpose may not have been clear - I will shortly go edit the wiki to see if I can make it clearer that this file exists. 

Additionally, the file config_template_basic.cfg in the same directory is a shorter version with only the options most commonly used. 

Further documentation of the config options is also available in the comments of:
https://github.com/su2code/SU2/blob/master/Common/src/config_structure.cpp

And although it has not been up to date as we moved towards the wiki and config file template rather than keeping doxygen up to date, additional documentation can be produced using the files in su2code/Documentation/Doxygen.

**Comment by ThomasHermann** [comment]
The canonical configuration file, 'config_template.cfg', is located in the source directory. It lists all of the commands and usually, at least for the configuration parameters I've been interested in, allowable values. Another good resource is the online discussion forum:

http://www.cfd-online.com/Forums/su2/

There is also the Github wiki for this project in the menu to the right >>>>>>

There is the source code. It was hard to write, so it might be hard to read, but the information is there.

Finally, as an open source project, this is an area where you could contribute for fame & fortune. You could collect the information from the various sources into a coherent document.

**Comment by GregVernon** [comment]
@hlkline 

Thanks!  That's what I was looking for -- I'd tried Google and was disheartened when this was the first response:
![image](https://cloud.githubusercontent.com/assets/868479/8146370/07259a96-11fa-11e5-8611-06d02d487c73.png)  

Which was a link to the official SU2 page stating: 
>Instead of writing a detailed user manual, the approach has been taken to teach the various aspects of the SU2 code through a range of tutorials.

I'd propose adding something to the effect of what you've said there.

@ThomasHermann 

Now I know where to start ;)  I think we can both agree that reading someone else's code and trying to make a user manual from scratch is a bit unrealistic -- I'll see what I can do with the config file though!
