### ISSUE TITLE
Undefined behavior in NDFlatner causing spurious values of wall roughness

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1893]
**Describe the bug**
I faced some non determinism in #1892 which I traced back to spurious values of walll roughness.
I tried running UB sanitizer and valgrind, the latter finds one memory error when accessing the flatner, but theres nothing while it's built.
The ndflatner unit test also fails on my machine, both in release and debug builds.

Given the complexity of that class, and it only being used in one place, I just wrote alternative code.
@maxaehle can you investigate the issue?

**Desktop (please complete the following information):**
 - ubuntu 22 + gcc + mpich (standard packages)

**Comment by pcarruscag** [comment]
In my case I need to build like this:
```
export CC=mpicc.mpich
export CXX=mpicxx.mpich
export CXXFLAGS="-march=native -funroll-loops -ffast-math -fno-finite-math-only"

./meson.py build --optimization=2 --warnlevel=3 -Denable-tests=true --prefix=$PWD/build -Dcustom-mpi=true -Dwith-omp=true
./ninja -C build install
```
Maybe building with OpenMP makes a difference.
The unit test output is
```
../UnitTests/Common/toolboxes/ndflattener_tests.cpp:78: FAILED:
  REQUIRE( nd3[r][0][0] == 0.7 )
with expansion:
  2.0 == 0.7
```
valgrind does not pick up anything on the unit test, only on the new test case added in #1892 
The expected output is as shown in hybrid_regression.py (note that the testcases branch is not develop).
When the UB manifests the residuals are not the expected (by varying orders of magnitude depending on the spurious value of wall roughness).

**Comment by pcarruscag** [comment]
Both the unit test and case are running without MPI, `SU2_CFD -t 1 primal.cfg` but with 2 or 4 threads it seemed easier to reproduce.

**Comment by maxaehle** [comment]
Thanks, with these build commands, I can reproduce the "`2.0 == 0.7`" unit test error in an MPICH environment, when running the test with a single MPI process (`mpirun.mpich -np 1`). For multiple MPI processes, the test passes in my current setup. The error persists when I disable OpenMP. When I use OpenMPI instead of MPICH, the test driver crashes for `-np 1` ("An error occurred in MPI_Win_create ... MPI_ERR_WIN: invalid window") but probably that is a different issue.

After some std::cout debugging, I suspect that the MPICH implementation of [`MPI_Allgatherv`](https://www.mpich.org/static/docs/v3.2/www3/MPI_Allgatherv.html) is not working as expected in the case of a single MPI process. 

I would expect that if there is only a single MPI process, `MPI_Allgatherv` copies `sendcount*sizeof(scalartype)`=`recvcounts[0]*sizeof(scalartype)` bytes from `(scalartype*)sendbuf` to `(scalartype*)recvbuf+displs[0]`, where `scalartype` is the C type represented by the MPI types `sendtype`=`recvtype`. This is the behaviour I had in mind when writing the NdFlattener code.

With [minimal.cpp.txt](https://github.com/su2code/SU2/files/10459977/minimal.cpp.txt) (remove the .txt), OpenMPI gives the following results:
```bash
$ mpic++ minimal.cpp -o minimal 
$ mpirun -np 1 ./minimal
Rank 0 recvbuf = -42 100 
$ mpirun -np 2 ./minimal
Rank 0 recvbuf = -42 100 101 
Rank 1 recvbuf = -42 100 101 
```
This is in line with the expected behaviour of `MPI_Allgatherv` described above. For MPICH however, I get:
```bash
$ mpicxx.mpich minimal.cpp -o minimal
$ mpirun.mpich -np 1 ./minimal
Rank 0 recvbuf = 100 0 
$ mpirun.mpich -np 2 ./minimal
Rank 0 recvbuf = -42 100 101 
Rank 1 recvbuf = -42 100 101 
```
as if `displs` were ignored for `-np 1`.

@pcarruscag Can you confirm this observation? Do you think that my understanding of the expected behaviour of `MPI_Allgatherv` is correct?

**Comment by pcarruscag** [comment]
:+1: Is there something that can be tweaked in the implementation of the NdFlattneer to mitigate this issue? Either avoiding displs[0] != 0 or handling the single rank case manually?

**Comment by maxaehle** [comment]
I could create a "safe Allgatherv" function, e.g. in [`mpi_structure.hpp`](https://github.com/su2code/SU2/blob/1b085062547ec5b066a28ddeeacf4907588f4f5a/Common/include/parallelization/mpi_structure.hpp) or in [`ndflattener.hpp`](https://github.com/su2code/SU2/blob/1b085062547ec5b066a28ddeeacf4907588f4f5a/Common/include/toolboxes/ndflattener.hpp). This function should check the number of processes, perform a simple copy if it is 1, and otherwise calls the regular Allgatherv. It would then be used [here](https://github.com/su2code/SU2/blob/1b085062547ec5b066a28ddeeacf4907588f4f5a/Common/include/toolboxes/ndflattener.hpp#L235) instead of `SU2_MPI::Allgatherv`.

**Comment by pcarruscag** [comment]
Sounds like a necessary compromise, I don't think that mpi versions of Ubuntu distros are updated very often

**Comment by maxaehle** [comment]
For the record, the single-rank MPICH Allgatherv bug demonstrated by the above minimal example is currently present in the main branch at pmodels/mpich@92106e39a3c7996c7c0797ba8e160824b41039b2, but hzhou/mpich@2b8c5c7dc4974fc471b446e6cc939936aa14fd8f in pmodels/mpich#6374 fixes it.
