### ISSUE TITLE
unable to run TestCases on SU2 4.1

### ISSUE THREAD

**Issue by alexp1729** [su2code/SU2#222]
All the TestCases seem broken when I try to run SU2 4.1 compiled from source. When I run the serial_regression.py and parallel_regression.py scripts, I get error messages like 

There is no geometry file (GetnZone))!

and mesh files like mesh_ONERAM6_turb_hexa_43008.su2 appear to be missing. When I copy one of these from a 4.0 sample directory (where everything worked) and rerun the test case manually by typing something like

mpirun -n 2 /mit/su2_v4.1/bin/SU2_CFD config_CFD.cfg

it works. Something seems to be missing that generates the mesh files but I'm no SU2 expert, I just install it for the real users. Thanks for any help.

                                                                                     Alex

**Comment by hlkline** [comment]
Thank you for your question.
The geometry files are stored in a separate repository, su2code/Testcases
due to repository memory limitations. The file structure is the same, so
when you check out the test cases repository into the same folder you will
get the necessary files in the right places.
To test whether the installation worked immediately, you can run the
quickstart tutorial which includes the geometry file already.

Details on this, and other information you will likely find useful are also
available on the wiki of the github repository:
https://github.com/su2code/SU2/wiki/Download

Cheers,
Heather


On Fri, Jan 8, 2016 at 3:51 PM, alexp1729 <notifications@github.com> wrote:

> All the TestCases seem broken when I try to run SU2 41 compiled from
> source When I run the serial_regressionpy and parallel_regressionpy
> scripts, I get error messages like
>
> There is no geometry file (GetnZone))!
>
> and mesh files like mesh_ONERAM6_turb_hexa_43008su2 appear to be missing
> When I copy one of these from a 40 sample directory (where everything
> worked) and rerun the test case manually by typing something like
>
> mpirun -n 2 /mit/su2_v41/bin/SU2_CFD config_CFDcfg
>
> it works Something seems to be missing that generates the mesh files but
> I'm no SU2 expert, I just install it for the real users Thanks for any help
>
>                                                                                  Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/su2code/SU2/issues/222>.
>



-- 
Heather Kline
NASA Space Technology Research Fellow
PhD Candidate, Aeronautics & Astronautics, Stanford University
BS Aerospace Engineering, Rensselaer Polytechnic Institute
kline.hl@gmail.com, hlkline@stanford.edu

**Comment by alexp1729** [comment]
Thanks! I was confused because the source distribution had a TestCases directory with a partial set of files. It might be less confusing if the source distribution didn't have this at all, and all the test files were in the TestCase repository.

                                                                                   Alex

**Comment by economon** [comment]
Alex, Heather,

Thanks for commenting and straightening this out. Since this is a frequently asked question, I have added a new section in the documentation on how to use the test cases, which will hopefully clear things up more in the future: https://github.com/su2code/SU2/wiki/Test-Cases.

Tom
