### ISSUE TITLE
My code is freezing at 20th iteration

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#273]
Does someone have any clue of a possible reason? Not quite sure what happens. 

Thanks,
Paul

…………………………………………………………………………………………….
   19   1.115647    -3.274987      5.238256      -0.000000      75.533935
   20   1.121534    -3.248678      5.217649      -0.000000      71.542545

**Comment by abdulhaq-e** [comment]
Is it freezing exactly at the iteration or when writing the restart/solution files?

**Comment by paulhzhang** [comment]
It happens at the iteration.

Thanks for response.

**Comment by abdulhaq-e** [comment]
Do you have any warning on "unphysical points"?

**Comment by paulhzhang** [comment]
Not at all actually. I found a bug later. A double ** pointer is not initialized, and some elements are given random numbers. 

Thank you very much for your kindness on this issue. 
Paul

**Comment by hlkline** [comment]
Would you mind letting us know where the double pointer is that has this problem? 
If you are using the master branch or an older release, you may also want to check if this problem was solved on the current developer branch - there have been a few recent updates to clean up allocation/deallocation. 
If you would like to submit your fix as a pull request (benefits include being recorded by Github as a contributer to this code), please look over the developer docs for instructions on code style, which branch to use, etc: https://github.com/su2code/SU2/wiki/Gitting-Started

**Comment by paulhzhang** [comment]
Sure. I am double-checking my code to make sure everything is all right before the pull request. Thanks for your comment. 
Paul

**Comment by hlkline** [comment]
We believe that issues related to uninitialized values have since been fixed; if you still see similar issues in the current version of the code, please feel free to open a pull request or re-open this issue.
