### ISSUE TITLE
A question about CNSSolver::BC_Isothermal_Wall

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#275]
For no-slip wall BC, the pressure term should be included in the inviscid flux, but I found none. Why?

Thanks,
Paul

**Comment by economon** [comment]
Hi Paul,

For the no-slip walls in SU2, we impose a strong boundary condition on the momentum equations, i.e., we explicitly set the wall velocity to zero (or to the velocity of the wall for dynamic mesh calculations). As we are setting the velocity condition directly, any residual contribution for the momentum equations at the wall is removed and the Jacobian entries for the momentum equations at that wall node are set to the identity matrix in order to fix the solution.

Hope this helps,
Tom

**Comment by paulhzhang** [comment]
Hi Tom,

That really helps. Except that, I got to know the iso-thermal boundary is set through a weak way, i.e. the heat flux is used to adjust the temperature at the wall vertex. 

Thanks,
Paul

**Comment by hlkline** [comment]
This appears to be resolved; please re-open if you disagree.
