### ISSUE TITLE
restart option with optimiser iterations

### ISSUE THREAD

**Issue by tpratt1993** [su2code/SU2#290]
when running an optimisation process, when the solution files are arranged in the /DESIGNS/DSN_001/DIRECT/ directory tree, if the option RESTART_SOLUTION is set to YES in the cfg file, the solution does not restart from a previous restart file! instead it simply deletes all old designs and runs the process from scratch again. 
for example: if i want to run the first N design iterations, then stop the process on the Nth iteration and change something in the config file -e.g. cfl num- (including setting the restart option to YES), upon resubmitting the job all N design iterations are lost and the process starts again from DSN_001.

this has proven to be quite an expensive problem for large 3D optimisations, and i am not sure wether this is a bug or something which has been hardcoded for a reason? 
it could be quite useful to have an option of where to restart the solution from? (e.g. restart from DSN_00X)
Cheers, T.P.

**Comment by hlkline** [comment]
Thanks for the question
The RESTART_SOLUTION option determines only whether the CFD solution will restart from a provided solution file, not whether the optimizer will restart. 
To restart the optimizer process, this must be specified to the python script:
shape_optimization.py -r project.pkl -f config.cfg -n N
The options of all the python scripts can be viewed with a command like:
shape_optimization.py -h

So, to run an optimization process restarted from a previous optimization, and to have each individual simulation restart from previously converged CFD results you will need to BOTH specify RESTART_SOLUTION and the -r python option. To restart the optimizer but have each CFD simulation start from scratch, use the -r option and specify RESTART_SOLUTION=NO. 

Restarting from a specified design (rather than the most recent design) is not currently provided as an option, but if you are willing to dig into things manually it may be possible via editing the project.pkl and results.pkl files. 

In the future, please view our forum at http://www.cfd-online.com/Forums/su2/, you may find questions about configuration options etc that have already been answered, and a wider community will be able to respond.
