### ISSUE TITLE
Sutherland's law

### ISSUE THREAD

**Issue by ghost** [su2code/SU2#301]
I have been researching about the Sutherland's law in different CFD codes. The form and coefficients vary depending on the implementation. Assuming a 3 parameters fit (there is a less popular 2 parameters version)

I. SU2 (SI units) is using:
MU_REF = 1.716E-5 kg / ms
MU_T_REF = 273.15 K
SUTHERLAND_CONSTANT = 110.4 K
from http://www.cfd-online.com/Wiki/Sutherland's_law

II. FLUENT is using 
MU_REF = 1.716E-5 kg / ms
MU_T_REF = 273.11 K
SUTHERLAND_CONSTANT = 110.56 K

III. The classical book "Viscous Fluid Flow" by Frank White (McGraw-Hill) proposes
MU_REF = 1.716E-5 kg / ms
MU_T_REF = 273 K
SUTHERLAND_CONSTANT = 111 K

IV. The NASA webpage https://www.grc.nasa.gov/www/BGH/viscosity.html and SU2 (US units)
MU_REF = 1.733E-5 kg / ms
MU_T_REF = 288.16 K
SUTHERLAND_CONSTANT = 110.4 K

And each CFD solver seems to use some slightly different parameters.

The difference between I, II and III is small...(%0.5) but large if we compare with IV (%3) (could be a typo in the NASA web page?)  

Sutherland's law is very important for SU2 because the nondimensionalization is based on the Reynolds number that typically comes from the viscosity (Sutherland's law again) that we compute from the Temperature evaluated using the Standard US atmosphere. If the viscosity formula that we use to evaluate Re is not consistent with the one that is implemented in SU2 we can find large discrepancies in, for example, the static pressure at the Far-field.

I have two recommendations: 1) US and SI should be consistent and we should use exactly the same number for both. 2) Instead of using an internet source I would use the values at White's book which is a classic and permanent reference.

I'll implement the change as soon as possible.

Best,
Francisco

**Comment by hlkline** [comment]
I certainly agree with using the most permanent/established reference for these values, and especially with consistent use within the code. 

Since viscosity is notoriously difficult to measure accurately, I suspect that the variations are due to using different data sets. In short, it may be more important to be consistent within the code than to pick the 'right' constants - and a user who places more trust in NASA's numbers than White's can manually change the constants through the config file as necessary.

Best,
Heather

**Comment by fpalacios** [comment]
Thanks Heather,

You are right, there is an uncertainty in the fit that comes from experimental data.  I'm going to triple check the number, in particular I'll check the original Sutherland's article, and I'll implement the modification. In particular, I'm very concern about the current difference between SI and US constants... we need to fix that as soon as possible. 

Unfortunately, this change is going to affect most of the regression test, I would appreciate some help... I'm not sure anymore about how to update the tests.

Thanks,
Francisco

**Comment by hlkline** [comment]
Certainly - I think that the newer regression tests that diff two files rather than using the values listed in the regression scripts are all inviscid, so I think this should just be a matter of updating the values in the regression scripts, and I can help out over email as well. 
If you haven't already seen it, there are some notes in the wiki as well: https://github.com/su2code/SU2/wiki/Running-Regression-Tests

**Comment by pcarruscag** [comment]
Not sure if this is still an issue or not, but these constants are configurable via the config, so I'll play the role of the stale bot and close the issue.
If the defaults need changing doing it just before releasing 7.1 would be appropriate.
