### ISSUE TITLE
how to restart an unsteady turbulent flow case (Double-check please)

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#302]
We need to restart with two files, which have index of like "a" and "a+1". One of them is for the state of the mean flow, and the other is for the turbulence. Am I right? 

I got this question because I actually ran a steady-state case and converged it to a solution. Then I would like to see the transient behavior. 

Thanks,
Paul

**Comment by economon** [comment]
Paul,

Thanks for the question, but this is probably better suited for the CFD Online forum since it covers code usage rather than development issues.

You need two complete states to restart the code if you're using 2nd-order dual time stepping. Just copy the final steady state restart (each restart contains mean and turb. state) so you have two copies and append the appropriate iteration number to the name. More here: http://www.cfd-online.com/Forums/su2/172105-restart-time-accurate-simulation.html.

Tom
