### ISSUE TITLE
A cell-based structure

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#309]
I was wondering if there is a cell-based structure for primal grid available in SU2, so the primal cells can be looped according to its index in each partition, and its centroid values can be averaged over all of the nodes surrounding it. 

Thanks,
Paul

**Comment by talbring** [comment]
The primal elements are stored in the CGeometry class in the array CPrimalGrid** elem (geometry_structure.hpp:114) which is of length nElem (which can be accessed with GetnElem()).

For future questions: please use the forum at http://www.cfd-online.com/Forums/su2/ otherwise we are going to have a lot of open issues here on github  ...
