### ISSUE TITLE
Question about constraints on the objective function

### ISSUE THREAD

**Issue by WillemFloris** [su2code/SU2#337]
Hi!

Currently I am optimizing 2D airfoil models for my master thesis. I did a small test with a naca0012 at AOA of 0 degree (Re = 0.7e6) just to check whether the optimization process works for this incompressible case.
I changed the objective function to drag, without any constraints. I aspected the optimizer to deform the airfoil shape untill a flat plate is reached, but this is not the case. It creates approximately 14 designs and after the 14th design, it starts over and it calculates the first design again. Furthermore the 14th design was just a small adjustment on the 1st design.
I am wondering whether there is an inbuild constraint in the code, which prevents the code to flatten out the airfoil totally.

Kind regards,

Floris van der Schuur

**Comment by hlkline** [comment]
Thank you for your question. Questions about use rather than reporting bugs and modification of the code are usually directed toward the forum at http://www.cfd-online.com/Forums/su2/

It sounds like the optimizer failed to improve the objective and returned to the initial point for that reason - possibly due to an inaccurate gradient. Some of the test cases are set up with a low number of iterations for testing purposes, but more convergence is needed in a real case. 

A thickness constraint can be applied. The type of design variables and the upper and lower bounds will also effect the results.
