### ISSUE TITLE
Test case failuring during postprocessing step not caught

### ISSUE THREAD

**Issue by hlkline** [su2code/SU2#341]
This is two, related, issues:
1. Currently there is some error during postprocessing, apparently mainly for unsteady cases, and occurring at the step where it is trying to read in the restart file. This seemed to crop up somewhere after build 711 . (within the last month, error does not occur at https://travis-ci.org/su2code/SU2/builds/174140107, and does in square_cylinder and other unsteady cases in https://travis-ci.org/su2code/SU2/jobs/181044438)
2. The regression tests did not catch this error - because the error occurs during postprocessing, and the regression test checks values obtained prior to that step, the regressions appear to pass in this case. Maybe a check on the output flow file, or introducing a check to catch any error output for all the tests. 

Labeled as priority since there seems to be a bug in unsteady post-processing.

**Comment by economon** [comment]
Thanks, Heather. I think this is related to PR #325, for which I believe Francisco has a fix. @fpalacios, did you already merge the changes you mentioned in the comments of that pull request into a different branch? I think we should get that merged into develop asap. I think we will also do a maintenance release shortly afterwards, since we have made a few bug fixes lately.

**Comment by hlkline** [comment]
Thanks!
If there's a current branch already being used for fixing minor issues, I wouldn't mind throwing in a couple of fixes to address compiler warnings that have started accumulating (mostly unused or uninitialized variables) into whichever branch that is rather than starting a new branch just for compiler warnings.

**Comment by tobadavid** [comment]
Hi,

Is that bug fixed somewhere (which branch) now ? I merged the current develop branch into my feature branch and SU2_SOL is still crashing for my parallel unsteady cases (no idea about steady cases).

Thanks !

**Comment by EduardoMolina** [comment]
Hi 

I am on the same page as David. Also, after restarting an unsteady case with more than 99999 it, the external iteration counter is messed up.

Eduardo



Enviado do meu iPhone

**Comment by hlkline** [comment]
Looks like this bug is not fixed yet. See pr referenced above for more thorough discussion of the causes and potential solutions. @fpalacios can you confirm whether you were working on this or if someone else should take a stab at it?
For the iteration thing; @EduardoMolina can you check into whether that is the same issue or if it's possible that it's coming from somewhere else?

**Comment by LaSerpe** [comment]
We knew there was a bug in SOL reconstruction since PR #325, and we also pin-pointed the problem (an array overflow).
In the discussion we had there we posted a possible solution though it is not implemented yet.
I believe @fpalacios is working on it to make it more robust and consistent with the rest of the code.
It is a small fix but I agree that we could definitely include it in the next pull request.

**Comment by arubino** [comment]
I am also experiencing this issue since today merge with develop. I have created a branch to fix this according to the suggestion of @LaSerpe  and made few tests. If Travis will pass, I am going to open a PR. Is that OK?
