### ISSUE TITLE
Bug in shape_optimization.py if RESTART_FLOW_FILENAME equals SOLUTION_FLOW_FILENAME

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#349]
If you run a shape optimization problem (shape_optimization.py) with the RESTART_FLOW_FILENAME config option equal to the SOLUTION_FLOW_FILENAME config option then in each design folder you get symbolic links to the solution in DSN_001 instead of the solution for this design iteration.

**Comment by hlkline** [comment]
My apologies that no one looked into this yet. 
I agree that this can be inconvenient; however I think in this case it is necessary for the code to be able to distinguish between the restart and solution files, since it is dealing with both at various points?
Have you come up with a work-around since posting?
