### ISSUE TITLE
Step size in finite difference script

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#367]
There is a problem with the finite_difference.py script. The step size is currently taken from the REF_LENGTH_MOMENT config option. See 

https://github.com/su2code/SU2/blob/develop/SU2_PY/SU2/eval/gradients.py#L470

I don't think that this was intentionally done. @fpalacios it looks like it was introduced with one of your commits (https://github.com/su2code/SU2/commit/90ab5347fc3071d44c0e9c2010a9faeacca0abc4)

**Comment by economon** [comment]
Bumping this issue. This has come up several times now for different people/projects. Is there a reason to keep it based on the reference moment length, or can we revert to specifying this through the command line options?

**Comment by fpalacios** [comment]
Hi,

Yep, I changed that. I know that from the math point of view it doesn’t make a lot of sense but, from the practical point of view, it is useful. 

There are some cases, in which computing gradients using finite differences is the only choice. And with the shape_optimization script it was not possible to control the step size for the finite differences. The option for step size was only in finite_differences.py.

The step size is scaled with the reference length because from the practical point of view, I have found that the size of the aircraft, wing, airfoil, is important to determine a meaningful step size. e.g. should we use the same step for an aircraft with a MAC of ~150in than for an airfoil with a chord of 1in.

Remember that most of the times we are using FD when the adjoint is not converging… so we have bad convergence of the direct problem (including some level of unsteadiness that we want to filter with the selection of the step size). In other words, with the right choice of the FD step size you can obtain, at least, an useful gradient… and that number is somehow linked to the size of the aircraft, wing, or airfoil.

The best solution would be to add the step size to the finite_differences.py and also to the shape_optimization.py (creating a new option in the config file)… not a top priority, but I’ll do it soon

Best,
Francisco

**Comment by juanjosealonso** [comment]
Agree with Francisco: the best solution is to have an input parameter that can be used to scale the FD step size.  I would suggest FD_REFERENCE_LENGTH to be created (and possibly specified in the config file).  If FD_REFERENCE_LENGTH is not specified, then it could default to REF_LENGTH_MOMENT.

Best,

Juan

On Mar 5, 2017, at 6:35 PM, Francisco Palacios <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Yep, I changed that. I know that from the math point of view it doesn’t make a lot of sense but, from the practical point of view, it is useful.

There are some cases, in which computing gradients using finite differences is the only choice. And with the shape_optimization script it was not possible to control the step size for the finite differences. The option for step size was only in finite_differences.py.

The step size is scaled with the reference length because from the practical point of view, I have found that the size of the aircraft, wing, airfoil, is important to determine a meaningful step size. e.g. should we use the same step for an aircraft with a MAC of ~150in than for an airfoil with a chord of 1in.

Remember that most of the times we are using FD when the adjoint is not converging… so we have bad convergence of the direct problem (including some level of unsteadiness that we want to filter with the selection of the step size). In other words, with the right choice of the FD step size you can obtain, at least, an useful gradient… and that number is somehow linked to the size of the aircraft, wing, or airfoil.

The best solution would be to add the step size to the finite_differences.py and also to the shape_optimization.py (creating a new option in the config file)… not a top priority, but I’ll do it soon

Best,
Francisco

**Comment by hlkline** [comment]
I also agree that there should be an explicit option, and that it should
default to the current behavior, however it may be more intuitive for the
user to specify the actual step size- people who don't have Francisco's
extensive experience will not intuit that the finite difference step will
be 1/100 of the reference length, and may have difficulty figuring that out
without help. I suggest something like FD_STEP_SIZE, either way with
documentation explaining it.
-H

**Comment by talbring** [comment]
I agree with Heather on that. It is only intuitive if you already have the experience. And in that case you know what an appropriate step size is, so you can also specify it directly without having it scaled by some reference length (and of course also consider the case where you don't have an aircraft, wing or airfoil).

**Comment by hlkline** [comment]
@fpalacios FYI this is included in https://github.com/su2code/SU2/pull/385. (I know you said you were going to add it, but I ended up needing to use that while checking over my code, and it turned out to be just a couple of lines). 
There was an option FIN_DIFF_STEP actually already in the configuration options, but just wasn't being used yet in the python code - I'm not sure who added that in, but thanks!

**Comment by talbring** [comment]
Solved in #385.
