### ISSUE TITLE
dv_size = project.config['DEFINITION_DV']['SIZE']

### ISSUE THREAD

**Issue by fpalacios** [su2code/SU2#378]
Hi All,

I’m a little bit confused with the python scripts and the design variable definition. It seems that to compute the number of design variable we use something like this:

```
    # number of design variables
    dv_size = project.config['DEFINITION_DV']['SIZE']
    n_dv = sum(dv_size)
```

I think that dv_size is new for me. Do you know what is the reason for this? Is it possible to put several design variable together in the output file and the python stuff will split the design variables?

Related with this, I have noticed several inconsistencies like:

We use:

```
    # prescale x0
    dv_scales = project.config['DEFINITION_DV']['SCALE']
    k = 0
    for i, dv_scl in enumerate(dv_scales):
        for j in range(dv_size[i]):
            x0[k] = x0[k]/dv_scl;
            k = k + 1
```
or this:

```
    # prescale x0
    dv_scales = project.config['DEFINITION_DV']['SCALE']
    x0 = [ x0[i]/dv_scl for i,dv_scl in enumerate(dv_scales) ]
```

Any clarification would be very appreciated.

Thanks!
Francisco

**Comment by hlkline** [comment]
I suspect this may have been related to some changes I made to allow
passing extra DVS to my multifidelity flowpath model. If that's the issue,
go ahead and take it out the offending code, if I decide to put it back in
I'll try to do it more cleanly. If it isn't urgent, I can look more into
this in a couple weeks.

On Feb 22, 2017 7:14 AM, "Francisco Palacios" <notifications@github.com>
wrote:

Hi All,

I’m a little bit confused with the python scripts and the design variable
definition. It seems that to compute the number of design variable we use
something like this:

    # number of design variables
    dv_size = project.config['DEFINITION_DV']['SIZE']
    n_dv = sum(dv_size)

I think that dv_size is new for me. Do you know what is the reason for
this? Is it possible to put several design variable together in the output
file and the python stuff will split the design variables?

Related with this, I have noticed several inconsistencies like:

We use:

    # prescale x0
    dv_scales = project.config['DEFINITION_DV']['SCALE']
    k = 0
    for i, dv_scl in enumerate(dv_scales):
        for j in range(dv_size[i]):
            x0[k] = x0[k]/dv_scl;
            k = k + 1

or this:

    # prescale x0
    dv_scales = project.config['DEFINITION_DV']['SCALE']
    x0 = [ x0[i]/dv_scl for i,dv_scl in enumerate(dv_scales) ]

Any clarification would be very appreciated.

Thanks!
Francisco

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/su2code/SU2/issues/378>, or mute the thread

**Comment by talbring** [comment]
I added this since we might have 3 directions per FFD control point. Instead of specifying them separately in DEFINITION_DV you can just set the direction of movement to (0,0,0) and it will expand to 2 or 3 variables in 2D or 3D, respectively.
