### ISSUE TITLE
Support for Vulkan compute API

### ISSUE THREAD

**Issue by muniix** [su2code/SU2#381]
Would be good to support the newer Vulkan compute api as this is showing greater performance and lower overheads.  Vulkan is also the prefered api for Aarch64.

**Comment by hlkline** [comment]
Thank you for the suggestion; if you are interested in implementing the changes necessary for SU2 to work with Vulkan GPUs please feel free to fork the code. 
Note that for the standard CFD computations, in many cases CPUs are preferable due to the balance between computation and communication between processors. GPUs become more advantageous for higher-order numerical methods.
