### ISSUE TITLE
Optimizing efficiency  (bug?)

### ISSUE THREAD

**Issue by WillemFloris** [su2code/SU2#395]
Hello!

Last week I ran a optimizing case, this time I optimized the efficiency of an airfoil (2D). 
According to @hlkline , the Python scripts automatically recognize the kind of objective and automatically distinguished the objectives which have to be minimized from the ones which have to be maximized. There is no need to scale the objective function by a negative symbol to change the optimizer from a minimum to maximum case, this is all done by the Python scripts, right?
However in my case the objective function values are all negative in the log.txt file, but not in the history file. Furthermore after  18 NIT, the optimizer stops and says that an positive directional derivative for line-search is found. Which should because otherwise the efficiency won't increase. Can you guys have a look at the log and history file, because I don't think the optimizer gives a right output (the FC of the log.txt and of the history file do not agree, it goes wrong between FC 56 and FC 67). 
I appreciate your help!

Kind regards,

Floris 

[history_project.txt](https://github.com/su2code/SU2/files/1018645/history_project.txt)
[log.txt](https://github.com/su2code/SU2/files/1018647/log.txt)

**Comment by talbring** [comment]
I don't see a real problem here. Efficiency is always maximized so in the python scripts the objective function is scaled by -1.0. That's why the optimizer output gives you negative values. Note that the optimizer always minimizes the objective function (therefore we need the scaling)!

I am closing this, but if you have any questions regarding this, please reopen this issue.
