### ISSUE TITLE
DV_value is not adjusted by the optimzer (incompressible flow regime)

### ISSUE THREAD

**Issue by WillemFloris** [su2code/SU2#409]
Hello SU2 users and developers,

Begin this year I noticed that the dv_value of an incompressible optimization case is not adjusted by the SLSQP optimizer, but is just halving for each function call. I executed th
e following test cases, to narrow the possibilities and to possibly detect the problem.  

First I took a compressible test case to see the deformation behavior of a compressible case; the behavior was as suspected. 
The next step is the change of regime type: compressible to incompressible, which results into a wrong behavior of the dv_value (halving for each function call). 
Subsequently I changed the regime from incompressible to compressible  and I changed only the velocity (not the Reynolds number) from Mach 0.7-> 0.07; dv_value worked as suspected. 
As last I ran the compressible case with Mach 0.07 and I changed Reynolds from 6.5e6 -> 1.6e6, which results in a wrong behavior (halving for each function call).

It seems to be a bug, because it is an unsuspected behavior and I do not see any relation between the regime type and the adjoint equations. I tried to find it in the code for weeks, however I could not find it. Can someone please tell me why the optimization process behaves in this way for incompressible flows. 

I saw many updates of SU2 to the adjoint scripts and to shape_optimization.py.  Now I am wondering whether this behavior has been taken into account during the update. So whether the incompressible optimizer will work properly after I have updated the SU2 package.

I really look forward to a solution or reply!

Kind regards,

Floris van der Schuur

**Comment by talbring** [comment]
Hi Floris,

the optimizer does not receive any information on the flow itself. The only information it gets are the objective function and the gradient. The optimizer is typically halving the dv_value if there was no sufficient decrease using the current step size for example if the initial scaling of the objective function was too large. So first of all try to reduce that factor (the number in OPT_OBJECTIVE). You probably need a different value for different regimes and Reynolds numbers as the magnitude of the gradient might be also different then.

If that does not help then I think that the reason for the behavior you describe is probably the accuracy of the gradient. Can you have a look at the convergence of the adjoint problem in all of the cases ? Otherwise you can also try the discrete adjoint (discrete_adjoint.py or -g DISCRETE_ADJOINT for shape_optimization.py).

Best,
Tim

**Comment by oleburghardt** [comment]
Let me briefly add that it might also be interesting to plot the sensitivities (you can find them in the surface_sens.dat-file in the folder for the adjoint calculation) for the incompressible and the compressible case:
If they are quite similar, but the ones calculated from the incompressible adjoint solution are more noisy, that would be some kind of confirmation of what @talbring suspects (which, I think, is right).
If they are not, there might be actually a problem with the solvers themselves.

For further localization of what's going wrong (or when the above idea didn't work out), the same procedure with the discrete adjoint solution for comparison could be interesting.

Regards, Ole

**Comment by oleburghardt** [comment]
Thanks for the additional information.

> This should give a difference in sensitivity results, 

Hm, I think some things should be clarified at this point because I think that it's possible that you mixed up two different step sizes:

- There is a step size that is used to **compute** the gradient when setting up finite difference quotients. That's a bit tricky, because although you are using an adjoint solution for the gradient computation, these are still used within the grid deformation. You can find it's value in the third column and since it's the same, the gradients agree.

- There is the step size belonging to the optimizer which **uses** the gradient (the one Tim refers to). It is influenced by the overall scaling of the objective function and agrees with the one you put above the gradients. This scaling factor determines the amplitude of the mesh deformation.

As Tim pointet out, the optimizer only 'sees' the objective function's value, its gradient and the scaling factor. It has no idea that there are some mesh deformations or aerodynamics going on in the background ;-). Therefore I find your result

> However the deviation of the sens_adjoint of incompressible is huge compare to the compressible case.

most important since it explains the different behaviour of the optimizer (and it's addionally not due to different values of the objective, since your CLift- and CDrag-values agree).

The remaining question is: Why are they that different? 
It could be due to distinctly different physics captured by the different PDEs (unlikely but possible), or due to (performance?) issues with the adjoint solver.
Fortunately, SU2 comes with an alternative adjoint solver (see Tims initial post how to run it) that can now help to find the reason.

Regards, Ole

**Comment by economon** [comment]
Hi Floris,

Can you clarify whether you are using the continuous or discrete adjoint?

One thing that I am noticing in your results above is the large difference in magnitude between the compressible and incompressible sensitivities on the surface, which could require very different scaling later when that info is sent to the optimizer... 

I would recommend running the discrete adjoint to get sensitivities for lift/drag w.r.t. the same set of design variables for both the compressible and incompressible solvers and comparing the result (with a nearly incompressible flow so the conditions are basically the same). This way, you can remove the scaling for optimization that is part of the shape_optimization.py script and focus only on the gradient results first. You could use the discrete_adjoint.py script for this.

Hope this helps,
Tom

**Comment by WillemFloris** [comment]
Hi Tom,

Thanks for your reaction! The previous simulations were all done by continuous adjoint. 
The current simulation is done according to your settings; scale =1, objective= efficiency, adjoint =discrete.
![image](https://user-images.githubusercontent.com/21182966/28562447-8f88c6e0-7122-11e7-882d-d861e34fe388.png)

In the discrete adjoint the difference in magnitude of the sensitivity is reduced. I will try to run the case for discrete adjoint as well, I will keep you updated.
Thanks for the help!

Kind regards,

Floris van der Schuur

**Comment by WillemFloris** [comment]
Hello guys,

I would like to inform you that I was able to run an incompressible optimization case successfully (for drag, lift and efficiency), by changing RESTART_FLOW to "YES", reducing the objective scale and increasing the scaling of DEFINITION_DV. For that reason this issue can be closed.

I would like to thank you again for helping me and giving me new insights of  SU2 and optimization.

Kind regards,

Floris van der Schuur
