### ISSUE TITLE
Spalart-Allmaras with  Rotation/Curvature Correction (SA-RC)

### ISSUE THREAD

**Issue by EduardoMolina** [su2code/SU2#410]
Hi folks,

I would like to add the SA with Rotation/Curvature correction in SU2, namely SA-RC according to the TMR (https://turbmodels.larc.nasa.gov/spalart.html). However, this model has a Lagrangian derivative of the strain rate tensor. How can I obtain the time-derivative in the dual-time stepping approach? Normally for steady simulations, this term is neglected.

Any help is really appreciated. 

Regards,

Eduardo Molina

**Comment by economon** [comment]
Eduardo,

Good question. I think you could do this by applying the same time discretization scheme as you employ for dual time-stepping, i.e., either first- or second-order backward difference, on the strain rate tensor. We could create extra storage for the strain rate tensor values at the N and N-1 time steps (the two previous time steps for second-order) so that you can compute the time derivative using the current N+1 value you are iterating on during each physical time step.

You might check out SetResidual_DualTime() in solver_direct_mean.cpp for more details.

Hope this helps,
Tom
