### ISSUE TITLE
Pressure-based incompressible solver

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#429]
Dear all,

I recently had a lot of discussions with people that are interested in developing a pressure-based incompressible solver (like SIMPLE etc.) in SU2. I just wanted to get the discussion started.

Who is willing to contribute ? What applications do you have in mind ?

**Comment by EduardoMolina** [comment]
Dear Tim,

I think it is good one. But we should keep in mind that we already have OpenFoam available which is a very good open-source solver for this type of flows, but I do not think it has an Adjoint solver. Please correct me if I am wrong.

Best,

Eduardo.

**Comment by vdweide** [comment]
Hi Tim,

In collaboration with the Energy Centre Netherlands (ECN) we are interested in participating in the development of a pressure-based incompressible solver. The applications we have in mind are all related to wind turbines, for which compressible solvers perform relatively poorly.

We realize that OpenFOAM is very much capable of carrying out such simulations, but the motivation for developing this in SU2 is indeed the availability of the (discrete) adjoint.

Regards,

Edwin

**Comment by koodlyakshay** [comment]
Hello all,

As a first step towards developing the pressure based system, I was looking at the Poisson solver currently in the code. Is there any active development going on in Poisson problem. From what I understand it was developed for electric potential problems. 
Is there some documentation or test case?

Cheers,
Akshay.

**Comment by koodlyakshay** [comment]
Hello,

I have now added a basic FVM implementation to solve a general Poisson problem. The existing Poisson solver used a FEM based discretization but we needed a FVM based discretization to maintain numerical consistency when the momentum equations and Poisson equation for pressure are coupled. The FVM based solver is now working but some work still remains (like output formatting, history files.. etc). I used a pseudo-time approach and Euler explicit and implicit schemes fortime integration. The source term and the boundary conditions (Dirichlet and Neumann) are all hard coded for now.

The next step would be to use the multigrid methods to solve the Poisson problem directly instead of the pseudo-time approach. 

Cheers,
Akshay

**Comment by oleburghardt** [comment]
Hi there,

maybe I should mention that as a part of my commits to integrate a CHT functionality to SU2 (see the pull request I opened up a month ago, if you like), I also had to implement a heat solver that can be coupled to a flow equation system. We even chose similar namings (mine is called CHeatSolverFVM).

It might be interesting for you that it also can be run "stand-alone" for pure heat conduction problems (for solids..) in which case it is nothing else but a Poisson solver.
It's just that my naming is unnecessarily specific, I should rather rename the CHeatSolverFVM to CAdvectionDiffusionSolver and generalize the coefficients ("diffusivity" instead of "thermal_difffusivity", for example). Sounds to be a good idea... :D.

Anyway, feel informed :-)

Ole
