### ISSUE TITLE
Multi-stage time integration schemes for multiple zones

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#437]
There is an issue for time accurate simulations with multi-stage time integration schemes in combination with multiple (fluid) zones. The reason is that the loop over the multiple (usually Runge-Kutta) stages takes place in the function CMultiGridIntegration::MultiGrid_Cycle, while the loop over the zones is carried out in the drivers. Hence the loop over the (Runge-Kutta) stages takes place inside the loop over the multiple zones. This is fundamentally wrong and will lead to at most 1st order accuracy in time. Hence, the sequence of these loops should be reversed.

In principle there are two ways to do this, namely moving the loop over the Runge-Kutta stages up in the hierarchy, or moving the loop over the zones down. I think the former option is undesirable, because this means that all the details of the different time integration schemes must be moved to the driver, which does not improve readability (to say the least). Furthermore, it leads to serious problems when more advanced time integration schemes (with time accurate local time stepping) are employed.

So therefore, in my opinion, the only practical solution is to move the loop over the zones downwards in the hierarchy. This leads to significant changes in the implementation, but does this lead to a fundamental problem for any of the applications of SU2?

Thanks,

Edwin

**Comment by salvovitale** [comment]
Dear @vdweide,

I clearly see  your point. However, this can be quite a big structural change of the code and I think we should plan very well how to address this issue.

The reason of having a driver class was to facilitate the extension of SU2 to multi-physics applications both for analysis (direct solver) and design (adjoint). Thanks to the high level of abstraction of the  CInterpolator,  CTransfer and the CIteration classes,  it was kind of natural to treat fluid-fluid problems similarly to multi-physics problem (i.e. fluid-structure and fluid-heat). As a matter of fact, the multi-stage turbomachinery approach , its adjoint counterpart, the sliding interface they all rely on this driver structure in which we loop among all the zones.

If i understood correctly, you suggest to move only the fluid-fluid multi-zone loop at lower level in order to integrate in time only after having coupled all the fluid zones. Right? If so, we need to design the code in such a way that the fluids zone loop is separated from the multi-physics one.
To solve this issue, I think,  we just need to find a smart way to differentiate fluid-zones from the rest. Perhaps we can do that by instantiating one Iteration per physics instead than per zone. So that inside the iteration we can couple all the fluid zones, and in the driver we can couple the different physics (Iteration). But it is just a preliminary idea.

In general I think we should aim to a structure that can flexibly accommodate multi-physics problems with multi-zones for different physics. An good example is solving fluid-structure in multi-stage turbomachinery, in which we have multiple fluid-zones and multiple structure-zones.  
    
I would like to hear on this matter also from @fpalacios  @talbring , @economon , @rsanfer  @oleburghardt ,@LaSerpe and @arubino.


Thanks @vdweide againg for raising this issue.

cheers

Salvo

**Comment by vdweide** [comment]
Dear @salvovitale,

I realize that it requires significant changes in the code structure and I don't have a clear answer how to do this, also because I don't know all the details of the implementation of the multi-physics simulations. 

The only thing I do know is that the loop over the zones must be inside the loop over the RK stages, at least for the fluid zones. Whether this is also the case for e.g. fluid-structure problems, I don't know. As you mentioned, the opinion of the other developers is greatly appreciated on this matter.

Regards,

Edwin

**Comment by rsanfer** [comment]
Dear @vdweide,

I do see your point as well, in fact I remember that I raised my concerns about this when the multi-physics driver started to be used for multi-zone, single physics problems. Unfortunately, moving down the loop in the zones would break the FSI solver, and also the FSI coupled adjoint solver that we have put together, so I have to advise otherwise. 

When we first put together the Driver structure, the objective was to be able to fully converge different physical problems independently from each other. Then, the level of abstraction of the classes we implemented permitted for the structure to be used in fluid-fluid problems. CFD is not my top expertise, so the details escape to me, but it always seemed to me more natural to have an upper loop on the physics (the driver loop), and then have an internal loop over fluid zones. 

That is pretty much the same idea as @salvovitale is proposing: keeping the Driver as is, for different physics, and incorporate inside the Iteration the loop over different zones in the fluid domain.  This structure would address problems like Salvatore's example of multi-stage turbomachinery.

Let's see what others think of this, happy to have a chat or a telecom over this.

Kind regards,

Ruben

**Comment by vdweide** [comment]
Dear @rsanfer,

I agree with you that the outer loop should be the loop over the number of physical disciplines involved in the problem and not the zones. Whether the individual disciplines contain one or multiple zones is irrelevant at this level, in my opinion. The loop over the multiple zones of a single discipline should take place at a much lower level, namely where the spatial residual is computed. At least, this should be the case for the fluid dynamics part. I don't know whether this is also the case for other disciplines, like structures.

What about the following high level structure?

- Loop over the number of iterations, or time steps for unsteady problems.
  - Loop over the number of pseudo-time steps for implicit time integration schemes
    (DT_STEPPING_1ST and  DT_STEPPING_2ND). For other cases this loop is 1.
    -  Loop over the number of disciplines involved
         Call iterate for each of the disciplines.
         In iterate: 
         - Loop over the (Runge-Kutta) stages
            - Loop over the zones of a single discipline
                 Compute spatial residual.
                 Update the state vector.
            - End loop over the zones of a single discipline.
           Exchange halo data. This includes the halo data between zones of a single discipline.
         - End loop over the (Runge-Kutta) stages 
    - End loop over the disciplines
  - End loop over the pseudo time steps.
- End loop over the number of iterations, or time steps for unsteady problems.

The weakness of this approach is that it still does not work when one would like to employ multi-stage time integration schemes for an unsteady, multi-disciplinary problem (does not work for the current implementation either), but maybe this is something we simply have to accept. The alternative is that all the details of the different time integration schemes have to be moved to the driver classes, which is highly undesirable, I think.

The structure above implies that the iteration_container and the integration_container should be defined per discipline and not per zone anymore. The geometry_container and solver_container should still be defined per zone.

Well, I suppose this leaves plenty of room for discussion, so I would say to continue the online discussion a bit further, such that things become a bit clearer how to tackle this issue. After that having a telecon would be good to iron out the details. 

Regards,

Edwin

**Comment by juanjosealonso** [comment]
All,

For whatever it is worth, here are some thoughts.  It is clear that we need to strike the right level and hierarchy of abstraction: at the highest level one really ought to be describing the physical problem, not the number of zones or the specific time-stepping algorithm that would be used.  But preventing future multi-zone calculations from reaching the (time) order of accuracy desired is also an important issue that SU2 must support (and that I think would be very important for those doing unsteady turbomachinery calculations).  Just as important: even for multi-physics problems (say fluid-structure interaction, when the fluid and structural solvers are not closely integrated into the same source) we need to ensure that the time accuracy of the full multi-physics calculation is as high as those of the component physics solvers.

This is a very valid and useful discussion and some proposals are on the table.  Given that we are planning a developer’s meeting sometime before the end of the year, this may actually be one of the items in the agenda for discussion, so some decisions can be reached that both make sense and minimize the pain of changes for any part of the existing code.  I would suggest that the conversation continue and that other proposals are put forward so the discussion can be finalized at the developer’s meeting.

Best,

Juan

On Sep 10, 2017, at 1:09 PM, Edwin van der Weide <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @rsanfer<https://github.com/rsanfer>,

I agree with you that the outer loop should be the loop over the number of physical disciplines involved in the problem and not the zones. Whether the individual disciplines contain one or multiple zones is irrelevant at this level, in my opinion. The loop over the multiple zones of a single discipline should take place at a much lower level, namely where the spatial residual is computed. At least, this should be the case for the fluid dynamics part. I don't know whether this is also the case for other disciplines, like structures.

What about the following high level structure?

  *   Loop over the number of iterations, or time steps for unsteady problems.
     *   Loop over the number of pseudo-time steps for implicit time integration schemes
(DT_STEPPING_1ST and DT_STEPPING_2ND). For other cases this loop is 1.
        *   Loop over the number of disciplines involved
Call iterate for each of the disciplines.
In iterate:
           *   Loop over the (Runge-Kutta) stages
              *   Loop over the zones of a single discipline
Compute spatial residual.
Update the state vector.
              *   End loop over the zones of a single discipline.
Exchange halo data. This includes the halo data between zones of a single discipline.
           *   End loop over the (Runge-Kutta) stages
        *   End loop over the disciplines
     *   End loop over the pseudo time steps.
  *   End loop over the number of iterations, or time steps for unsteady problems.

The weakness of this approach is that it still does not work when one would like to employ multi-stage time integration schemes for an unsteady, multi-disciplinary problem (does not work for the current implementation either), but maybe this is something we simply have to accept. The alternative is that all the details of the different time integration schemes have to be moved to the driver classes, which is highly undesirable, I think.

The structure above implies that the iteration_container and the integration_container should be defined per discipline and not per zone anymore. The geometry_container and solver_container should still be defined per zone.

Well, I suppose this leaves plenty of room for discussion, so I would say to continue the online discussion a bit further, such that things become a bit clearer how to tackle this issue. After that having a telecon would be good to iron out the details.

Regards,

Edwin

**Comment by vdweide** [comment]
Juan,

Indeed, it is desirable that at the highest level the details of the time integration scheme and number of zones per discipline should not be visible. The question is whether that is achievable for all combinations you can think of. This is especially the case for the time integration schemes.

E.g. suppose you would like to use a multi-stage time integration scheme for a multi-physics problem. To obtain the design accuracy in time, this implies that the loop over the number of time stages is outside the loop over the number of physical disciplines. Hence at a very high level in the hierarchy, the details of the time integration should then be known. The situation becomes even more complicated when one would like to employ time integration schemes that allow for time accurate local time stepping, e.g. the ones we are currently working on for the DG solver. I won't bore you with all the details here, but those schemes basically require the loop over the multiple disciplines to be between the predictor and corrector step, while both these steps consist of multiple stages.

Although it is probably possible to come up with a data structure that supports all this, the question is whether this is desirable. Apart from the fact that it would require a major overhaul in the high level design of SU2, the implementation will be less readable, especially for people that will be starting with the code. Also the parallelization may become significantly more complicated.

The alternative is that for unsteady multi-physics problems, we put the restriction that only single stage time integration  schemes can be used, e.g. DT_STEPPING_1ST and DT_STEPPING_2ND. In that case, the details of the time integration scheme can be hidden at the driver level, where we then simply have a loop over the number of physical disciplines. The consequence of course is that more advanced time integration schemes will not be available for multi-physics problems.

In the above I just tried to picture what, in my opinion, the consequences are for either option. I don't have a preference for one of them. The only thing I wanted to make clear is that it is not possible to hide all the details of the time integration scheme at the driver level, while also having support for all possible time integration schemes for an unsteady multi-physics problem.

Regards,

Edwin

**Comment by vdweide** [comment]
BTW, all of the above also applies for the grid motion parameters. This should also happen inside the loop over the number of stages of the time integration scheme and currently this is done outside this loop.

Edwin

**Comment by economon** [comment]
Hi all,

This is definitely good discussion... everything goes toward multi-physics nowadays, so we should always be improving the class design accordingly. I suppose this will just get more important with adding more physics, zones, and more complex time integration schemes.

I would like to highlight that when the code was first released, we did not have "zones" at all (not until some early sliding mesh work after a couple of versions), and the CDriver and CIteration classes didn't even exist until we dreamed them up a couple of years ago. My point is that, with some proper planning, we have the creativity and the right team to develop the solution we need, and we shouldn't be afraid to make big changes when necessary. Moving quickly while leveraging the team's broad skillset is one of our biggest advantages in this project.

As you all know, over the years, we continue to move toward a *_structure.cpp and *_physics.cpp mindset for how we do our abstractions/data encapsulations, with "structure" components reused and "physics" components being specialized to a certain set of governing equations. This has happened in many places, including recently with the CTransfer class, for instance, and it is likely to happen with the COutput class(es) before long.

However, one area where there hasn't been much evolution is within the CIntegration classes. Apart from a couple of additions for structural problems and now the DG integration, it is largely the same as it was in the first release. Perhaps this is our opportunity to rethink and update these classes for future expansion, just as we've done for others over the years. We could rework them, move them up or down in the hierarchy, change where they're instantiated, change the inheritance, and so on. Even if they get a little more complicated (like usual), as long as they're properly abstracted, it isn't likely to bother the developers working in other areas of the code too much. In short, I think some effort spent on the CIntegration classes could help here, and they are due for some updates anyway.

Tom

**Comment by vdweide** [comment]
Hi Tom,

Sounds like a plan then to have a look at CIntegration to see what we can do to generalize the time integration. I definitely want to help with this, but I don't think I am the appropriate person to take the lead, because I simply don't have a good overview of all the multi-physics options. Tom, are you willing to take the lead for this?

Furthermore, it is good to have other people involved as well, preferably with detailed knowledge of the different disciplines. Any volunteers?

Thanks,

Edwin

**Comment by talbring** [comment]
Hi all,

as with the restructuring of the output classes, we should find a common level of abstraction for all the different physical problems we might want to have.

Right now there isn't even a unified way of specifying the kind of problem for each zone (what is fluid, what is solid etc) and the kind of coupling. This might also affect the actual implementation/restructuring since we somehow have to decide what driver we have to instantiate and so on. Hopefully we can gather all the people involved to have a discussion on that.

Since we have a lot of people working in their branches on multizone problems we should tackle that better sooner than later.

As Edwin already suggested, maybe it is a good idea to put some people in charge of organizing some of the bigger structural changes.

Furthermore in case some people don't know, we have a slack channel for the dev team. I think that makes it easier to communicate, arrange meetings, discuss problems and ask questions. In case you need an invite, let me know, everybody who wants to contribute is welcome.

Thanks for the discussion, I still think that communication is the key of success !


Tim

On Sep 13, 2017 10:30 AM, Edwin van der Weide <notifications@github.com> wrote:

Hi Tom,

Sounds like a plan then to have a look at CIntegration to see what we can do to generalize the time integration. I definitely want to help with this, but I don't think I am the appropriate person to take the lead, because I simply don't have a good overview of all the multi-physics options. Tom, are you willing to take the lead for this?

Furthermore, it is good to have other people involved as well, preferably with detailed knowledge of the different disciplines. Any volunteers?

Thanks,

Edwin

**Comment by vdweide** [comment]
I had a discussion with @economon today and we agreed that the best thing to do is to implement the multi-zone, multi-stage stuff in a separate driver for now. In this way the current functionalities will not be harmed. If the implementation of the new driver is successful we may consider changing other drivers as well.

Thanks for the discussion on this issue,

Edwin
