### ISSUE TITLE
Possible bug in python FSI routine FSIInterface.py

### ISSUE THREAD

**Issue by RoccoBombardieri** [su2code/SU2#449]
Hello,

I detected a bug trying to launch the routine fsi_computation.py. As it is, the code doesn't work and crashes with an error saying that in FSIInterface.py the function call (setSolidInterfaceLoads):

**SolidSolver.applyload(iVertex, Fx, Fy, Fz, time)**

only requires 5 input arguments (not 6).

A deeper investigation showed that in PitchPlungeAirfoilStructuralTester.py the function is so defined:

**def applyload(self, iPoint, fx, fy, fz):**

so, no _time_ variable allowed or requested. After applying this correction the code works. 

Hope this can be of any help.

Best,

**Comment by tobadavid** [comment]
Hello,

May I ask which version of the code do you use and on which branch ? In fact, this bug (and it was not the only one) was already fixed a few days ago on the branch feature_pyWrapper. You may pull those new changes just to be sure to have a clean version. Otherwise, I would not trust the results.

The reason why the FSI Python tool (note the distinction with the SU2 Python wrapper, which is maintained and up-to-date) accumulates some bugs is that, normally, it is not really maintained anymore in prevision of a new coupling framework. I recently introduced some fixes to make it work again (I mean the coupling SU2 + pitch-plunge structural solver) in the meantime, but you may want to double-check each result you get.

Best,

David

**Comment by RoccoBombardieri** [comment]
Hi David,

Actually I was using the first official release of the Raven version of SU2 (I think released at the end of this February). I'm mainly interested in the python tools of the package as I'm dealing with fluid structure interaction. Thank you so much for the advice, hope the branch you suggested me is ok for my purposes!!

Best,

Rocco

**Comment by gabrielebedon** [comment]
HI David,

I am sorry to bring up this topic again, but I am experiencing the same bug from Rocco and I found this Issue discussion. However, I can not find the branch "feature_pyWrapper" that you mentioned. Is it still somewhere?
I am presently using the official 5.0.0 release cloned from the main branch.

Thanks
Best Regards
Gabriele

**Comment by tobadavid** [comment]
The feature_pyWrapper branch has been removed, since it was recently merged into the develop branch (#488). Just check out the develop branch instead of master and compile the code again. Everything should be ok. Be sure to _git fetch_ the repo before switching on the develop.

Best,
David
