### ISSUE TITLE
Parallel run of the python routine fsi_computation.py

### ISSUE THREAD

**Issue by RoccoBombardieri** [su2code/SU2#457]
Hello,

I'm pretty new to python and, in general, to the logic of parallel computation. 
I'm trying to run in **parallel** the routine fsi_computation.py. Even if (as much as I noticed) the parallel computation feature is already built in the structure of the code I'm not able to do it. Moreover, I find the structure of the routine sensitively different than the one of parallel_computation.py in which, for example, I can actually choose the number of processor I can use for the run.

Dose anybody know if the feature is actually implemented in fsi_computation.py and, in case, how to set it?

Thanks!

NB: I'm currently using the version of the code provided in the branch **feature_pyWrapper** which, as it was already told me, is the up-to-date version for the the python tools.

**Comment by tobadavid** [comment]
Hi,

The structure of fsi_computation.py is completely different from the one of parallel_computation(_fsi).py, this one is just a script that, if I am right, will set for you the commands in order to launch SU2_CFD in parallel and SU2_SOL right after. It is based on system calls ( it is like calling mpirun -np xx SU2_CFD SU2conf.cfg and mpirun -np xx SU2_SOL SU2conf.cfg).

The fsi_computation.py has to be considered as an executable, and thus has to be launched with the mpirun command for parallel run:

$ mpirun -np XX fsi_computation.py -f FSIConfig.cfg --parallel

You have to specify the FSI configuration file (see examples in TestCase) with -f, and the --parallel option is mandatory (only if SU2 has been built in parallel). XX is the number of procs.

Hope this helps,

David

**Comment by RoccoBombardieri** [comment]
Thanks David! (for the second time! :) )
Rocco
