### ISSUE TITLE
Add the option to specify an inlet profile from a table of values

### ISSUE THREAD

**Issue by clarkpede** [su2code/SU2#467]
This is a feature request based on [some previous discussion](https://github.com/su2code/SU2/commit/61e810d4459ba56879d90b997c25723819f8352b#comments) on the `feature_inletprofile` branch.

I've got a working prototype on [a branch](https://github.com/pecos-hybrid/SU2/tree/feature_inletprofile_file) off of my group's fork.  Here's a few key points:

+ _Data structures to store the inlet conditions already existed_.  On the develop branch, there's arrays in `CEulerSolver` such as `Inlet_Ttotal`.
+ Previously, the `CEulerSolver::BC_Inlet` was doing a set of string compares every single iteration to find the inlet values.  Pulling values from arrays should be faster.
+ I am _not_ taking the same approach as in the `feature_inletprofile` branch.  The existing inlet profile branch adds another inlet type to the existing two.  Instead, I added a separate option.  That way, you can both specify an inlet type (e.g. `TOTAL_CONDITIONS` or `MASS_FLUX`) and decide if you want the inlet to be uniform or specified by a file.

The branch is a little rough for the following reasons:

+ The user must manually specify the inlet conditions at each inlet node by listing the node number.
+ Interpolation of nodes is not supported (yet).
+ Multigrid is not supported.  I tried to find a simple way to do this, but it's a more difficult problem than I thought.

I could submit a pull request now, if the lead developers want me to.  But I'd like to take some more time to run further tests.

**Comment by economon** [comment]
Great progress, thanks @clarkpede !

As for your notes, some thoughts:
- I think you are already doing this but just in case... manually specifying the info at each node can be made a little easier by automatically generating the files for the first time if they don't exist at runtime. We had code that would do this for the grid motion case, and perhaps you can reuse it to generate inlet profile files with the correct global ID and dummy free-stream state to save the trouble of finding the global IDs by hand (that is what we wanted to avoid as well). Then you can at least use excel or another text editor to swap out the data.
- I wouldn't worry about interpolation to start. This can be added later.
- MG is a little tough, but I think we should be able to do a mapping down to the coarse levels in a similar way that we do the restarts in the volume mesh. Can you please check the code in LoadRestart() in solver_direct_mean.cpp where we restrict the solution down onto the coarse levels?

**Comment by economon** [comment]
@clarkpede : I would like to collaborate with you to wrap up the C++ implementation of this feature (I know you have already completed the Python version). If you have some time, can you please push your version to an internal branch of the SU2 repository?

**Comment by clarkpede** [comment]
@economon I need to fix and test a few things before I push the branch to an internal branch.  But I should be able to finish by the end of the next week.

If you're looking to improve the C++ inlet profile specification I started, then I'd like to get some feedback on the overall design.   There are several different ways to handle this, and I chose what I thought was most logical. I want to make sure that my design choices match your use cases and SU2's design. Should I post a summary here, or would you prefer that I email you?

**Comment by economon** [comment]
Thanks, @clarkpede : no need for too much overhead on your part. It doesn't have to be perfect and please don't spend too much effort with prep (there's no judgment, all progress is good progress!). I can take some time to diff through the changes you've made myself too.

Let's post any comments here in the open so others can join in if they'd like.

**Comment by clarkpede** [comment]
Alright.  I've copied over my changes, with a few improvements.  They're on the branch `feature_fileprofile`. One important change is that the user no longer needs to specify the node numbers.  For each inlet node on the mesh, the code looks for the closest point from the inlet file.  If that closest point is within a specified distance, it deems it a match.  If not, it returns an error.

Some points:

+ The code will generate an example inlet file if the inlet file is missing / is invalid.
+ I have not added interpolation.  Since python makes interpolation easy, I didn't view this as a high priority.
+ I have not added support for multigrid.  I'm unsure of how to do this, since I'm not familiar with the multigrid code.  It's not as simple as copying what's done for the restarts in the volume mesh.  That's a volume based agglomeration, whereas the boundaries are faces.

Feel free to modify my implementation however you want.

**Comment by economon** [comment]
Thanks @clarkpede, I'll take a look...

**Comment by economon** [comment]
I just pushed a new version of your inlet profile branch. I really like the solver class abstractions. I can tell you have a good grip on the classes and where data should live - nice job.

Here are the changes I have made:
* everything is generalized in parallel for an arbitrary number of inlets in the file. The file format changed slightly.
* I moved around some routines and data to take more advantage of inheritance and encapsulation: it is now more like the restart routines where the reading and data live in the parent CSolver class, the specific load functions are found in the solvers (I overloaded SetInletAtVertex), and the template file is written by COutput. It is written such that any solver could eventually use it for any marker type by adding the appropriate SetInletAtVertex routine for solver-specific data (might need to rename for different marker types rather than inlet) and writing an appropriate template file writer in the output.
* for now, it is still requiring a essentially a matching profile point (nearest neighbor within a tight tolerance) by default, but you can have an arbitrary number of points in the file for each marker, and we can eventually add interpolation easily. We already have some of these routines.
* the turbulent solvers now all use the Inlet_TurbVars data structure even for uniform inlets. Can you please check this with Python?
* multigrid is now working. I put in a boundary face area-averaged restriction operator for the inlet profiles. Any decent approximation on the coarse levels should work ok.

I left all of your original routines there, but deactivated them for the moment. Can you please give it a look and let me know what you think (and whether it is working for you)? Feedback most welcome. If we are happy with it, we can clean it up and submit a PR.
