### ISSUE TITLE
Multiple runs launched with parallel_computation.py

### ISSUE THREAD

**Issue by alexfeld** [su2code/SU2#469]
When using `srun` version 15.08.7 `parallel_computation.py` launches `-n` instances of my SU2 call rather than one instance of SU2 with `n` processes. This does not happen with `srun` version 2.6.5. I fixed this issue by commenting out the line in `interface.py` that calls `srun` if a SLURM jobID number is in the environment variables. This causes `parallel_computation.py` to call `mpirun`, which works as expected.

**Comment by talbring** [comment]
You can override the command that is used to launch parallel jobs by setting the environment variable `SU2_MPI_COMMAND`. For example on our cluster I had to force it to use the usual mpi command with `export SU2_MPI_COMMAND="mpirun -n %i %s"`, otherwise it tried to use `srun` which didn't work with our setup.

**Comment by samcom12** [comment]
Thanks for your help :) I followed it exporting MPI Command and then running parallel_computation.py. Everything works fine but when I use slurm to submit jobs to HPC cluster I couldn't get much speed up with increasing number of nodes. 

Please refer attached  slurm script.
[slurm_script_su2.txt](https://github.com/su2code/SU2/files/2205463/slurm_script_su2.txt)

**Comment by ugurtan666** [comment]
I have the same problem but I don't understand the solutions you suggested. Could you explain to me a bit clear?
