### ISSUE TITLE
Broken links - Example mesh generation files.

### ISSUE THREAD

**Issue by cwcatkins** [su2code/SU2#476]
Hi, 

I have just tried to download square.cpp from the page:

https://github.com/su2code/SU2/wiki/Mesh-File

however, get a "Not Found" 404 error. Is this file still available?

Kind Regards,

Chay

**Comment by economon** [comment]
Thanks for letting us know - the links are now fixed! Take care,
Tom

**Comment by koodlyakshay** [comment]
Hi,

The square.f90 file doesn't write the elements correctly for the "left" marker. The loop counter is doesn't go all the way to zero and only 2 elements are written. 
Currently reads 
   do jNode = mNode-2,mNode-3,-1 ....
instead of 
   do jNode = mNode-2,0,-1 ....

I think there is the same issue in the square.cpp file too. 

Akshay.
