### ISSUE TITLE
The training page: The page you are looking for cannot be found.  404

### ISSUE THREAD

**Issue by Foadsf** [su2code/SU2#512]
When searching for SU2 tutorials the first page is
[https://su2code.github.io/training.html](https://su2code.github.io/training.html )
and it is broken!

**Comment by economon** [comment]
@Foadsf: thanks for the note. We recently completed a major overhaul of the project website (https://su2code.github.io) in order to consolidate everything into a single, open repo so that everyone can contribute. Some pages were shifted around, but I expect the search engines should flush the old pages before long. Please check out the new documentation and tutorials pages here (closing this issue for now):

https://su2code.github.io/docs
https://su2code.github.io/tutorials
