### ISSUE TITLE
Travis issue with regression tests

### ISSUE THREAD

**Issue by rsanfer** [su2code/SU2#524]
Hi all,
I'm experiencing some issues with travis lately, not only with time-outs (already discussed a few times), but also with this message:

_No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself._

_Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated_

It appears to happen randomly, and I noticed that this happened as well to the latest develop build. Anyone that could give any input on this matter?

Thanks,
Ruben

**Comment by rsanfer** [comment]
Ok, thanks Tom! It's that "silence" time which was confusing for me, because it seems to happen at random. Let's wait to see the possible solutions.

**Comment by economon** [comment]
The folks at Travis CI have kindly doubled both our "hard" timeout and "silence" timeout limits up to 140 min. and 20 min., respectively. We should be safely within limits for some time to come. 

That being said, rather than relying on the increases, I would really encourage that we find some better approaches for reducing total test time, as we will continue to add more cases. It is not good for our pace of development that we have to wait over an hour to get the results of the tests. I think that a test time of approx. 10-20 min. would be more ideal so that we can iterate much more quickly. I suspect that attacking our compile time would be most helpful.

Any ideas and discussion most welcome.

**Comment by rsanfer** [comment]
That's great! At least it gives us some margin to solve this issue. I agree that we should try to reduce the time of the tests. I think that @talbring approach a few months ago of reducing the number of iterations was the correct one; the tests don't need to be physically meaningful, but rather technically representative of the features. The compile time is also something that we should look into - we might need to have a telecom on this.

**Comment by WallyMaier** [comment]
@all this still continues to be an issue.  The current pull request altering only the config_template is getting timed-out.
