### ISSUE TITLE
Sign Error in `GetViscousProjJacs`

### ISSUE THREAD

**Issue by clarkpede** [su2code/SU2#609]
I believe there's a sign error in how the Jacobian of the viscous fluxes is computed for ideal gases.  If you're not familiar with the code, there are two variants: one for ideal gases, and one for arbitrary equations of state. The code for ideal gases is not consistent with the code for arbitrary gas laws.

In ``CNumerics::GetViscousProjJacs`` for the ideal gas law you'll find:
 
    val_Proj_Jac_Tensor_i[4][0] += factor*proj_viscousflux_vel;
    val_Proj_Jac_Tensor_j[4][0] += factor*proj_viscousflux_vel;

In ``CNumerics::GetViscousProjJacs`` for arbitrary gas laws you'll find:

    val_Proj_Jac_Tensor_i[4][0] -= factor*proj_viscousflux_vel;
    val_Proj_Jac_Tensor_j[4][0] -= factor*proj_viscousflux_vel;

The term is added for ideal gases, but subtracted for non-ideal gases.  After deriving the Jacobian myself and having a colleague check my work, I believe that the form for arbitrary gas laws is correct.  The ideal-gas law variant seems to be incorrect.

Moreover, the code in `GetViscousProjJacs` could use some cleanup.  I propose both correcting the sign error and cleaning up the code to be readable.

**Comment by hlkline** [comment]
This sounds like an important thing to fix, and it looks like you've done some serious work to confirm it. 
Would you mind putting your changes into a pull request?

Since the ideal gas version has been around for longer, I would initially suspect that there is another sign flip somewhere else in the code for some reason (which may be hard to find... especially if the code needs some cleanup). Just in case, I suggest running a verification case with both versions, using the ideal gas law as the 'arbitrary' equation of state, and comparing against the built-in ideal gas, under both versions of the code, in order to confirm that the result changes to be the same when the sign is changed as you suggest. Ideally, something that can be compared to results from another code or to experiment to confirm that the sign-corrected version is correct, especially since I'm guessing this will effect a lot of regression tests.

Code cleanup is of course always appreciated as well.

@salvovitale & @LaSerpe since it looks like you've worked on the real gas version: any comments, and do you have a viscous test case?

**Comment by clarkpede** [comment]
Writing a simple unit test is difficult, since SU2 both doesn't have unit tests and wasn't written with unit testing in mind.  That being said, I've got a unit test that I'm happy with.  Our group has put our own unit-testing framework into our fork of SU2, based off of Boost and automake testing.  The unit test I created runs off of that framework.  That means it won't run out-of-the-box on the develop branch of SU2.

When I run the unit test with no changes to `CNumerics::GetViscousProjJacs`, I get that the residuals and Jacobians match to within 10 times the machine epsilon, aside from the [4][0] value of the Jacobians.  There, the relative difference is of the order 1E-6.

When I switch the two lines in `CNumerics::GetViscousProjJacs` for ideal gases to be negative, the tests run with no complaints.  Ideal gas and generalized variants match to within 10 times machine epsilon.

I'm uploading my test file just as an example, in case anyone wants to see what I've tested.
[viscous_ideal_vs_general.zip](https://github.com/su2code/SU2/files/2590517/viscous_ideal_vs_general.zip)

As for comparison to some results from another code, I think that's a lot to ask.  Getting a good comparison would depend on an understanding of how the ideal gas model, viscosity, numerics, and Jacobians are handled in the external code.  Small differences would make the comparison completely invalid.  I completely support testing and checking the changes I'm proposing.  But comparison with an external code seems to provide a very low return on investment.

**Comment by economon** [comment]
As Jacobians affect convergence rate and not accuracy, you could do a quick test of the same problem with the current version and the sign flipped to see if there is measurable difference in the convergence rate. If yes, then it should give you a hint about which direction. If no, then we should still correct it, but prob don't need to put in too much effort.

@clarkpede : I'm interested in your unit testing set up...

**Comment by pcarruscag** [comment]
@juanjosealonso , @talbring ,
The jacobians are pre-accumulated when running in AD, is there an easy way to dump them and compare with what is comming out of the numerics?

**Comment by LaSerpe** [comment]
All, 
I just went briefly through the code and it doesn't seem that there is some hidden sign flip somewhere else.
Those signs were originally changed in the push made on Sep 20, 2014.
In that push, Salvo originally added the 'arbitrary' function and he changed the sign in the ideal one, possibly because he recognised that as a bug.
Probably the fix was then reverted in a later merge, I'll try to have a look at this and double check it.

By the way, the numerics*.cpp need some clean up for sure, as @clarkpede was pointing out.
I also believe that we could manage to gain efficiency and get some (not much) speed-up by restructuring this part of the code.

Best,
Giulio

**Comment by clarkpede** [comment]
@economon I tested a couple of simpler problems at subsonic speeds, including the ONERA M6 case at M=0.8395.  There's occasionally a difference of one iteration out of about 20.  Usually the current develop branch is the one that requires more iterations, but not always.  I included a snapshot from my tests on the ONERA M6 case at CFL=30.

![convergence_comparison](https://user-images.githubusercontent.com/13340225/48648855-6c97af80-e9b6-11e8-863a-56dfdf0903c8.png)

I don't have a good supersonic, viscous test problem, but I suspect the differences in convergence won't be huge there either.  This sign change affects a single term out of many and a single component of a 4x4 or 5x5 Jacobian.

My take is that the differences are there, but they are very small.  I wouldn't have noticed the problem myself if I hadn't been refactoring the code to enable some changes on our end.

**Comment by hlkline** [comment]
This looks good; with repeated and well-checked analytical derivations plus numerical checks, and given the scale and impact (a single line of code, and a slight change to convergence rate), if this was in a pull request I would approve it. 
@juanjosealonso, @pcarruscag the AD information is still worth getting, and sharing the process of how to get it, since I'd guess that would be very useful for checking similar problems in the future - just maybe not as a reason to delay this specific change.

I've seen accidental reversions in the past, I think it's something we should all keep an eye out for when reviewing pull requests. @LaSerpe thanks for tracking down the history on the changes.

For unit tests: agreed, those would be very useful and I would be interested in seeing them too. 
For short term/ad hoc purposes, another option that hasn't been mentioned in this thread is using a debugger to inspect the values as the code runs.

**Comment by clarkpede** [comment]
This was resolved by PR #612.
