### ISSUE TITLE
Consolidation of communication channels

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#645]
Please join the [slack](https://slack.com) workspace by clicking [here](https://join.slack.com/t/su2devteam/shared_invite/enQtODE2MzQ1MTk4NDA0LWYxNzM0NGM0YTMxNWY0NmY5NDU2YzllNGJlMmU2ZTU0ODJiNWExZDNkZjdiMTNlMjE5OWRjNzI3OGM1OWFkOTE).

This enables direct communication with the developers! Still, please use Github Issues for reporting bugs and feature requests.

**Comment by hlkline** [comment]
Given that this isn't the first attempt at consolidating communication & discussion threads (including slack and SU2 IDS); could you describe in a little more detail how the discussions on rocket.chat will be different from those on github threads like this one, or from the threads on cfd-online/forums/su2?

I'm sure it's a great service, and I can tell that you've put a lot of thought into what to use, I just feel like it's the third or fourth time I've had to sign up for something new just in order to stay in the loop, and each time I get a little more concerned that I will end up accidentally missing the next platform change and never hearing SU2 news again (which would make me sad - I know i haven't been participating much lately, but I do often read the pull request discussions when an interesting one pops up in my email). 

FYI, the SU2 IDS website seems to be down - is that temporary or has it already been retired? If rocket.chat works out, will that mean that both slack and SU2 IDS will be retired?

**Comment by economon** [comment]
@hlkline : it is true that we have been experimenting a lot to find the best formula, and no doubt we will continue to tweak things as we constantly evolve. But, one constant you can always trust is that the repo will be the home for important decisions on issues and PRs, so there is no need to worry about missing critical updates. 

With slack and now rocket chat, we are looking to improve communication efficiency as people collaborate on particular developments in the code (say in pairs or small groups), or perhaps in the future, it can be opened to the public as a sort of support channel. This is to be seen as we gather some experience and feedback.

**Comment by marcovanderbijl** [comment]
Status?
At may 21, 9AM europe time
I am getting a 
"This Workspace has been Stopped"
message from URL
https://su2.rocket.chat/

**Comment by talbring** [comment]
Hi @marcovanderbijl 

unfortunately the trial phase ended ... we currently in contact with the guys at rocket chat to see whether they can further support us!

**Comment by talbring** [comment]
For the time being, lets use Gitter to communicate! Its free and you can simply log in with your github account. https://gitter.im/su2code/community

**Comment by erangit** [comment]
There might be a problem here: If I understood correctly once you login to Gritter using your GitHub account, it opens all the git access that you have to all the community that is in the Gritter group.
I have, and probably other people also do,  access to GitHub locations (other than SU2) which are not open for the public (like Github of commercial companies). In the Gritter login page, I could see all these locations but could not remove those that are not SU2 related.

**Comment by talbring** [comment]
You have to restrict third-party access in the options of the other project (https://help.github.com/en/articles/enabling-oauth-app-access-restrictions-for-your-organization)

**Comment by talbring** [comment]
Seems like none of the solutions really worked. I would then suggest we go back to Slack. How do people think about that ?

**Comment by talbring** [comment]
This is the link to the "old" workspace: https://su2devteam.slack.com 
I'll be online there, so if someone wants to chat :smile:

**Comment by talbring** [comment]
Then I would say lets reactivate that. Link is posted under discussions or click [here](https://join.slack.com/t/su2devteam/shared_invite/enQtODE2MzQ1MTk4NDA0LWYxNzM0NGM0YTMxNWY0NmY5NDU2YzllNGJlMmU2ZTU0ODJiNWExZDNkZjdiMTNlMjE5OWRjNzI3OGM1OWFkOTE).

**Comment by talbring** [comment]
I know we had some back and forth with communication platforms. But we will stick to slack now. Just as a friendly reminder, please consider joining. Discussion/Announcements and so on will happen there. I still think that communication is the key for success :)
