### ISSUE TITLE
MAX_NUMBER_FFD = 15

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#684]
I found that SU2/Common/include/option_structure.hpp sets a limit on the number of FFD boxes
MAX_NUMBER_FFD = 15;	     /*!< \brief Maximum number of FFDBoxes for the FFD. */

Is there a reason for this limit or can I simply set it to a higher value and recompile?
I would like to have 65 boxes (that would make one box per wing segment for the wing that I am designing). But I think I can work with 20 boxes If 65 is really to much for the program to handle.

**Comment by economon** [comment]
@marcovanderbijl : thanks for the question. The original limit there is simply to impose an upper bound for memory considerations, since the first instantiation of the array of FFD boxes (before the number of FFD boxes embedded in the mesh is detected) needs a default value. We can of course change this to automatically detect the number to avoid the requirement or make it an input option in the config, but we have not run into this issue yet.

For now, you should be able to increase that to a reasonable number without any issue. Please give it a try.

**Comment by marcovanderbijl** [comment]
thanks! should I close issue,.. or will someone take it up and code auto FFD box number detection?

**Comment by economon** [comment]
Let's leave it open for now, since it is a straightforward feature request.

Did you have luck with adjusting the max number of boxes?

**Comment by marcovanderbijl** [comment]
yes, as expected it compiled without a warning. But as yet untested because there seems to be much terribly wrong with getting FFD_TWIST to work.
