### ISSUE TITLE
question about   grid_movement_structure.cpp   SetFFDTwist

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#693]
I had a look at CSurfaceMovement::SetFFDTwist in grid_movement_structure.cpp

It starts with geometry->SegmentIntersectsPlane where the segment is the axes/line of rotation and the plane is the jPlane of the control points we wish to move.
However, unless the axes is EXACTLY parallel to the plane then there is always an intersection point (though maybe far in the distance), so why would this check be done. Unless there is also a check on how far away the intersection point lies, but this is not done.

Then there is this comment with theta calculation:
/*--- The angle of rotation is computed based on a characteristic length of the wing,
       otherwise it is difficult to compare with other length based design variables. ---*/
su2double RefLength = config->GetRefLength();
su2double theta = atan(config->GetDV_Value(iDV)*Scale/RefLength);
Where theta is calculated with the atan of DV_Value, implicating that the DV_Value is a distance,.. though in my knowledge setting the twist of an airfoil in the wing (or in our case the twist of a jPlane in the FFD box) is always done with a rotation in degrees/radians.
What is the programmer trying to do here?

Then there is the calculation of the rotation itself, that is done with the intersection point of the rotation axes with the plane, and the normal vector of the control point in the plane. Thus indicating that this normal vector is used as the orientation of the rotation axes. Though the plane normal and the rotation axes direction ought not to be of the same orientation.

Looking back in the code from SU2-4.3.0 SetFFDTwistAngle would do a better job I think, where theta = config->GetDV_Value(iDV)*PI_NUMBER/180.0 indeed using an angle of rotation as value. And also indeed using the set rotation axes to rotate the jPlane about.

**Comment by jannav984** [comment]
Hello,
is there any reply? What I understood from the original post, the DV value for FFD_TWIST is not straighforward. 
Why it is not taken in degrees? The comment says: _/--- The angle of rotation is computed based on a characteristic length of the wing, otherwise it is difficult to compare with other length based design variables. ---/
It could be easily done in reversed sense. Is there anything what I miss?
Nevermind, the config file comment could be done in better way, to help user understand the design variable setting. 

Jan
