### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#696]
**Is your feature request related to a problem? Please describe.**
This is more a question. Has anybody tried to use the parallel binary IO for large files, i.e. larger than 2 Gb? Especially for the reading of the restart files I expect problems, as MPI_Type_indexed uses standard ints for computing the offsets.

**Describe the solution you'd like**
A test, or a confirmation from somebody, to check if parallel binary IO of large files works fine.

**Describe alternatives you've considered**
None. If large files give problems we should consider alternative constructions with MPI IO that do work. I expect that people will run into this limit soon (if not already now).

**Additional context**

**Comment by economon** [comment]
@vdweide : I have not hit this issues yet, although I have not been paying too close of attention to the file size (although I have used some large ones). We can make a quick test of this with free stream through a very large cube mesh. 

This also goes hand in hand with large mesh support, in my mind, since you won't care about the restart files if you can't get your large mesh loaded :). We can add this to the list for the RPSVV group.

**Comment by vdweide** [comment]
@economon, I expect to run into problems for grids containing around 250 million DOFs, depending a bit on how many variables you store in the restart file. We can definitely do this test with a dummy grid. As you added this to the RPSVV group, let's close this issue here.

**Comment by economon** [comment]
Actually, let's open this back up so that it stays in the list in the RPSVV project. Otherwise the automation moves it to "Done"

**Comment by economon** [comment]
WIP
