### ISSUE TITLE
run in docker

### ISSUE THREAD

**Issue by noisystreet** [su2code/SU2#747]
I have built SU2 in docker and run several cases, but some of them failed  at _MPI_Waitany_ . Will there be officially support for a docker release version of SU2 ?

here's the Dockerfile I used to build SU2.

[Dockerfile.txt](https://github.com/su2code/SU2/files/3449693/Dockerfile.txt)

**Comment by talbring** [comment]
Please have a look here #738 and here #739.

**Comment by talbring** [comment]
And we will eventually provide container images using Singularity soon. However, we first have to find a proper way of running the python scripts in parallel from outside of the container.

**Comment by stephansmit** [comment]
@talbring 
Is this problem (of not being able to run the python scripts in parallel from outside the container) described in an issue somewhere?

**Comment by talbring** [comment]
Well thats not really an issue. Its just a conceptual thing. Usually what you want to do with an container is to run something from the outside like
```
./container_binary <arguments>
```
or to be more specific, like I did with the singularity container
```
./su2.sif SU2_CFD configfile
```
This way you can also run the python scripts
```
./su2.sif parallel_computation.py -f configfile
```
This works well in serial, however, if you want to run it in parallel you probably should use mpirun from the host system (actually I have no idea what happens if you run mpirun inside of the container, but I am pretty sure that it won't work properly on a cluster). But: at the moment the python scripts do exactly that at the moment, they call the binaries using mpirun in the container.

**Comment by stephansmit** [comment]
While playing around with the singularity containers a little bit, what do you think about this solution?

Execute the python script inside the container with the python on the host
~~~~
singularity exec su2_container.sif cat /SU2/ | python3
~~~~

Adjust the python interface (SU2_PY/SU2/run/interface.py) to execute the container:
~~~~
# set mpi command
if user_defined:
    mpi_Command = os.environ['SU2_MPI_COMMAND']
elif slurm_job:
    mpi_Command = 'srun -n %i %s'
elif singularity_job:
    mpi_Command = 'mpirun -n %i singularity exec %s'
elif not which('mpirun') is None:
    mpi_Command = 'mpirun -n %i %s'
elif not which('mpiexec') is None:
    mpi_Command = 'mpiexec -n %i %s'
else:
    mpi_Command = ''
~~~~
