### ISSUE TITLE
Better Documentation Strategy

### ISSUE THREAD

**Issue by WallyMaier** [su2code/SU2#775]
While running test cases, I noticed the slope limiter is not defaulted to none.   This caused me a bit of headache trying to figure out why a simulation wasnt behaving as expected.  I can imagine the defaulted can cause problems for many users, particullarly with new users.   I think in the remake of the config_template in #772 , the defaults should be made more clear.

**Comment by WallyMaier** [comment]
I noticed the addition of the Guide to V7 page being introduced to the SU2 page. I think this would make a great starting point to beef up our documentation/tutorial pages.  Using a similar format, we could discuss the available options in SU2.  Speaking from experience, new SU2 users face an extremely high learning curve, often scaring them away.  I believe this would help alleviate that problem.

I understand this is no small task, and welcome others thoughts on the issue

**Comment by bmunguia** [comment]
From the SU2 paper, talking about "guiding principles":

<img width="574" alt="Screen Shot 2019-10-09 at 3 26 46 PM" src="https://user-images.githubusercontent.com/19416354/66525312-edb5d480-eaa9-11e9-9c0f-158b3941b407.png">

I particularly like

> Full documentation, including a comprehensive set of tutorials

("including" implying that the tutorials are a subset of the documentation), and 

> expose the full set of options [...] to the practitioner

This conflicts with our "operating principle", laid out on the tutorials page:

> Rather than writing a long manual on all available (and constantly evolving) configuration options available in SU2[...]

The Guide to V7 is a good start, but I think at the bare minimum (since I agree that full documentation would be a huge task, though one that's apparently promised on a paper we link on our homepage), we should provide more information about the existing options beyond forcing the user to scroll through config_template.cfg or dig through the tutorials.

**Comment by talbring** [comment]
There is no doubt in the fact that we need a better documentation. My idea was to have sections where we at least describe the basic settings (like the one I already started https://su2code.github.io/docs/Solver-Setup/) which are common to all solvers. Furthermore short paragraphs on each individual solver (including a brief theory). 

Basic things could include:
- Markers and Boundary Conditions
- Monitoring Coefficients
- Defining the numerical methods

Please lets not start a big discussion on that. Lets rather invest that time in actually doing it.

**Comment by WallyMaier** [comment]
I think the Solver Setup page is a great start, I think it will go a long way.

**Comment by talbring** [comment]
This is another example:
https://su2code.github.io/docs/Markers-and-BC/

Its not much work but adds a lot of value I think. Feel free to add whatever you think is necessary.

**Comment by pcarruscag** [comment]
@talbring are you ok with having best-practices or common errors interleaved with that documentation?
For example, careful when switching from Euler to RANS and not updating this or that boundary condition.

**Comment by talbring** [comment]
Yep sure! I think that is exactly what will give it more value compared to the `config_template.cfg` file

**Comment by economon** [comment]
All: we will need all the help we can get to make a big documentation push for v7. Please do take some time and contribute to the new structure that @talbring is setting up. Even if you only have some time to work through the new documentation and find/correct typos or issues you find. I will be adding some governing equations to the solver sections very soon.

As for documenting the config options, the best policy is that it is automatic. As has been done with the output and the dry run mode (-d), we can also do the same for all config options. They can be made self-describing by adding their description/comment directly into the code that creates the option in the C++, which can then be printed on request with a -h flag (or something similar). This is no doubt the way to go in my mind. But, that will likely be for after v7, so for now, let's invest in the docs, since they are critically important.

**Comment by WallyMaier** [comment]
I think this is being done! Thanks @talbring and @pcarruscag for their work on the docs page.  I think with the docs, we can close this issue.
