### ISSUE TITLE
Invscid Supersonic Wedge test case similar .su2 mesh and cfg but different results

### ISSUE THREAD

**Issue by irahulsonkar** [su2code/SU2#890]
Generated .su2 mesh using Gmsh with same number of elements and nodes as .cgns mesh have on "su2code.github.io/Inviscid_Wedge/" repository and used same configuration file from the repository but results are different on using .su2 mesh from Gmsh and the one downloaded from repository. 

Its weird that both the mesh are exactly same and same cfg file but different shock resolutions (repository mesh give smoother result). Please check attached Mach contour generated using Paraview.
![MachContour](https://user-images.githubusercontent.com/59632055/75407996-ce83ea80-5957-11ea-8b7c-9c1a731d7a84.png)
[mesh_and_config_files.zip](https://github.com/su2code/SU2/files/4259257/mesh_and_config_files.zip)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - MPI implementation and version:  MicrosoftMPI v10.1
 - SU2 Version: v7.0.0 (binary executable)

**Comment by saurabhtalele** [comment]
Sir, i have take different geometry but for me why shock is not appeared
https://drive.google.com/folderview?id=12MLnHnDqJaqyKpvCYsnU92MA44A19Db0

**Comment by irahulsonkar** [comment]
> Sir, i have take different geometry but for me why shock is not appeared, i have used GMSH to make transfinite mesh but
> https://drive.google.com/folderview?id=12MLnHnDqJaqyKpvCYsnU92MA44A19Db0

It seems there is some problem with your boundary markers. Please check if you have placed inlet, outlet and wall properly.

**Comment by saurabhtalele** [comment]
sir, now I have same problem that you have

**Comment by pcarruscag** [comment]
Looks can be deceiving. What you are seeing there are post processing artifacts.
Mostly because the meshes are coarse, but also because the grid from the tutorial is nicely ordered (the points follow the mesh lines right to left then top to bottom (or some permutation thereof) same for the elements) whereas the Gmsh grid is all jumbled up :)
Which means that despite the points being in the same places (actually they are not, there are tiny differences), the two grids are not actually "equal". The connectivity is different and this will change the order in which SU2 traverses the domain, which will result in small (of the order of machine accuracy) differences.
But if you export the results in CSV format (`OUTPUT_FILES= RESTART_ASCII`), and compare results at matching locations, you will see that they are not different.
