### ISSUE TITLE
Spurious results with AUSM & Venkatakrishnan limiter over RAE2822 Airfoil

### ISSUE THREAD

**Issue by aeroamit** [su2code/SU2#917]
[RAEairfoil_AUSM_issue.pdf](https://github.com/su2code/SU2/files/4375761/RAEairfoil_AUSM_issue.pdf)
**Describe the bug**
I was trying to run RAE2822 rans case with AUSM scheme (SU2-7.0.1). I observed some issue while using Venkatakrishnan or Venkatakrishnan-Wang limiter, spurious pressure distribution over the surface along with pressure contours in the field are observed. While with Van Albada edge limiter, results are smooth (Kindly see the attached pdf). I tried changing Limiter coefficient value also, it did not help. But other variants of AUSM (+-up/up2)  go fine with Venkatakrishnan limiter. 
Is there any catch here?

**To Reproduce**

[turb_SA_RAE2822.cfg.zip](https://github.com/su2code/SU2/files/4375817/turb_SA_RAE2822.cfg.zip)

**Desktop (please complete the following information):**
 - OS: [e.g., Linux (Ubuntu 16.04)]
 - C++ compiler and version: [g++ (GCC) 5.4.0]
 - MPI implementation and version: [Open MPI v1.10.2]
 - SU2 Version: [v7.0.1]

**Comment by erangit** [comment]
Hi @aeroamit 
I have encountered that problem before (in previous releases) using the Venkatakrishnan-Wang limiter for high Mach number cases. Had similar experience like yours, where Van Albada performed better. I think theoretically the  Venkatakrishnan-Wang limiter should be better and this is why, to my opinion, it is the default option. Van Albada is a good reliable old work horse, also in other codes. Still, we might have some problem in the implementation of  the Venkatakrishnan-Wang limiter,

**Comment by aeroamit** [comment]
Hi @erangit 
Thanks for sharing the info. I stumbled upon this while comparing AUSM and its variant results for this problem. It appears with both Venkatakrishnan and Venkatakrishnan-Wang limiters for AUSM (not its variants up/up2).
Also as you mentioned, there may be a need to have a re look in the implementation (or otherwise it may be the behaviour of this combination). 
Regards
Amit

**Comment by pcarruscag** [comment]
The limiters were re-implemented in #834, if anything pops up do let me know.
The current (and previous) implementation just consists of taking the minimum value of the limiter function over all edges connected to a vertex...
For your specific case the limiters are active in the regions with oscillations.
Curiously if you run first order the oscillations do not disappear completely (but they are smaller) so I think you are mostly seeing artifacts of AUSM (or the mesh since the oscillations align with the grid lines).
There are not-so-subtle differences between how AUSM and AUSM+UP combine the left and right states (especially on coarse grids), it could be worth trying to convert AUSM to the general formulation of AUSM+UP(1/2) and SLAU(1/2) we currently have. I can help, but I do not have time to run the tests.

**Comment by aeroamit** [comment]
I ran the cases ([RAEairfoil_AUSM_issue2.pdf](https://github.com/su2code/SU2/files/4395223/RAEairfoil_AUSM_issue2.pdf)) with 1st order and 2nd order accuracy (Van Albada limiter). @pcarruscag , as you mentioned the oscillation are small. They are visible if you zoom in close to the wall (very small). This may be attributed to AUSM scheme. But fortunately, oscillation do not show up in pressure distribution  (both 1st and 2nd order).
While combination of AUSM+VENKATAKRISHNAN limiter is resulting in much more pronounced oscillations.

**Comment by pcarruscag** [comment]
A similar issue was mentioned during the conference (Van-Albada behaving better), having done some testing recently my opinion is the following:
- Contrary to Venkatakrishnan, the Van-Albada limiter is always "active" even in relatively smooth regions.
- Node-based limiters take the minimum value over neighbors, whereas edge-based limiters use two limiter values per edge.

Therefore Van-Albada is more conservative and also more differentiable (no min function).
One could experiment with:
- Computing the minimum value over neighbors using a differentiable function.
- Trying the edge-based approach with the Venkatakrishnan-type limiter functions.

**Comment by aeroamit** [comment]
Hi everyone, I am commenting to bring it out from stale issue. Probably Dr. Pedro have been trying something, edge based Venkatakrishnan limiter (mentioned in previous comment).

**Comment by pcarruscag** [comment]
I'm not a Dr. yet, even then just Pedro will be fine.
I played with that idea a little, it was not very good, maybe because the smooth function was never designed to work in the negative region.
I also tried modifying the Van Albada function to disable limiting in smooth regions, to get close to Venkat-Wang on the NACA0012 case I had to disable limiting almost everywhere in the domain.

**Comment by aeroamit** [comment]
Hi Pedro, shall I close this issue or we should continue (wait for other's input as well ...) . Also you had an observation that the oscillations are probably due the basic nature of scheme (as they were present in 1st order results as well). These oscillations aren't observed with AUSM+-up/UP2 anyways...

**Comment by pcarruscag** [comment]
Yes I suppose it can be closed, maybe you can try this problem again when there are news from #1050
