### ISSUE TITLE
Unclear line in Turbulent Solver, is it correct?

### ISSUE THREAD

**Issue by stephansmit** [su2code/SU2#918]
While trying to get a stable converging solution for a 3D turbine with tip clearance, i stumbled upon the following line in the CTurbSolver (line 413).

```
su2double Delta = Vol / ((nodes->GetLocalCFL(iPoint)/flowNodes->GetLocalCFL(iPoint))*flowNodes->GetDelta_Time(iPoint));
```

It's unclear to me why the two CFL numbers are divided by each other. In case of running with a constant CFL this ratio will always be one. So the Delta value for the turbulence solver will become independent of the CFL number. Is this correct?

**Comment by bmunguia** [comment]
Delta_Time is only set for the flow, and already includes the flow CFL number, so this is just scaling the time step based on the flow and turbulent CFL. But yes, this ratio would always be one (even for adaptive CFL, @economon can correct me if I'm wrong?) because in `CSolver::AdaptCFLNumber()` we have
```
solverFlow->GetNodes()->SetLocalCFL(iPoint, CFL);
if ((iMesh == MESH_0) && (config->GetKind_Turb_Model() != NONE)) {
  solverTurb->GetNodes()->SetLocalCFL(iPoint, CFL);
}
```
Maybe Tom had something in mind when storing separate CFL numbers and scaling, but never got around to it so just left them equal? If you want a different turbulent CFL, the option `CFL_REDUCTION_TURB` still exists so you could probably add a `config->GetCFLRedCoeff_Turb()` and see if that helps.

**Comment by pcarruscag** [comment]
I recently (yesterday) found that that option does not reduce anything at the moment.
I've re-enabled it, the fix will be in one of my ignored PR's.

**Comment by economon** [comment]
> Delta_Time is only set for the flow, and already includes the flow CFL number, so this is just scaling the time step based on the flow and turbulent CFL. But yes, this ratio would always be one (even for adaptive CFL, @economon can correct me if I'm wrong?) because in `CSolver::AdaptCFLNumber()` we have
> 
> ```
> solverFlow->GetNodes()->SetLocalCFL(iPoint, CFL);
> if ((iMesh == MESH_0) && (config->GetKind_Turb_Model() != NONE)) {
>   solverTurb->GetNodes()->SetLocalCFL(iPoint, CFL);
> }
> ```
> 
> Maybe Tom had something in mind when storing separate CFL numbers and scaling, but never got around to it so just left them equal? If you want a different turbulent CFL, the option `CFL_REDUCTION_TURB` still exists so you could probably add a `config->GetCFLRedCoeff_Turb()` and see if that helps.

@bmunguia is correct.. I was experimenting with adapting the CFLs independently for the two systems to further improve convergence, but did not have time to find a stable solution. So, I left the framework as-is to accommodate this at some point.

**Comment by stephansmit** [comment]
@bmunguia @pcarruscag @economon thank you for your fast reponses. Copied the lines from the mentioned PR for now to include the CFL_REDUCTION_TURB
