### ISSUE TITLE
Inlet Interpolated File output varies with mpi cores

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#944]
The inlet interpolation capability that I introduced #815 is working as expected with one or few cores.

For a case that I have, if I go beyond 5 cores (mpirun -n 6) the output Interpolated File has a lesser number of lines printed. There should be 5517 lines but going beyond 5 reduces them to ~3000 lines (Each line representing a node at the inlet).

My best guess is that the interpolation is happening correctly but during the cout for the interpolated file, something goes wrong. I tried rank==MASTER_NODE before calling the PrintInletInterpolatedData() but that didn't resolve the issue.

Is this only a cout issue? How can this be resolved?

Thanks in advance.

**Comment by pcarruscag** [comment]
At some point the marker starts being partitioned, some of it is in one rank, some in other(s).
Your print function truncates the file when it opens it, and so you only get the output from the last rank that opened the file.
You could make the file a member of the class, so that you can guarantee it is only opened once, but then you still have a race condition when multiple ranks try to write simultaneously to the file (the result might be mixed lines, especially when `endl` is used to terminate lines because it forces a flush).
To my knowledge mpi does not have simple ways to guarantee ordered execution of certain code regions. So unless you want to get knee deep in mpi, I recommend you keep this file output as a debug feature (that works on a single core) and use the surface output files (paraview, tecplot, etc.) for visualization.

**Comment by auzbaig** [comment]
That's right. Thanks for your input.
