### ISSUE TITLE
Thrust coefficient and other rotating frame coefficients not written correctly on the screen or history file

### ISSUE THREAD

**Issue by koodlyakshay** [su2code/SU2#957]
**Describe the bug**
The values of Total CT, CQ and CMerit are computed by the flow solvers but are never written on the screen or the history file. These coefficients belong to the ROTATING_FRAME group and I am not able to find this in any of the output classes. I can see functions for aero coefficients and marker_analyze, is there an equivalent function for these coefficients?

**To Reproduce**
Any problem run with rotating frame. For ex, I have attached an example cfg file here
[centrifugal_blade.txt](https://github.com/su2code/SU2/files/4542348/centrifugal_blade.txt)

The mesh is from TestCases/turbomachinery/centrifugal_blade/su2mesh.su2

 - SU2 Version: v7.0.3

**Comment by economon** [comment]
You are right. Even though we compute these quantities inside the solver, they have not been added to the output classes yet. This should be straightforward though now in the new structure.

Take a look at CFlowOutput::SetAerodynamicCoefficients(), for example, and try to pattern match to add these along with the others since we already have a ```solver->GetTotal_CQ()``` routine (and CT and CMerit) to access the computed value. Probably also need to add to the AddAerodynamicCoefficients() routine.

**Comment by koodlyakshay** [comment]
Ok, will do. Thanks.
