### ISSUE TITLE
Shape Optimization Issues

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#976]
I want to discuss some important issues I have encountered while running shape optimization.

1. After some design iterations, the **periodic boundaries are not exactly matching**. A bad match is found until after some design the linear solver diverges. Is the shape optimization architecture in SU2 not designed to maintain the periodicity of the boundaries?

2. If I want to **perturb a single design parameter by a certain amount and deform the mesh**, what is the parameter in the config file that I can change for that?

3. My optimizations seem to **run independently of what I set as the OBJECTIVE_WEIGHT**. My understanding is that a negative value means minimization of the objective function and vice versa. However, with OBJECTIVE_WEIGHT=-1, the optimization seems to increase my objective function rather than reduce it. In the config_DOT_AD (and other configs), the objective weight was still +1 so I believe it wasn't being parsed correctly. I had to hardcode all instances of OBJECTIVE_WEIGHT in the C++ and python scripts from +1 to -1 to resolve the issue (which it did in the configs), however, the optimization direction is still opposite to what I want.

4. The DV_Value is always 0.001 in the config files. What is this value and is this hardcoded? 

5. In the _of_grad_*_ file the third column is for _"FINDIFF_STEP"_ = DV_Value. Does it mean that the grid deformation wrt to control points is done via finite differences?

**Problem specific details,**

**Case:** Single blade row stator passage with inlet profiles

OBJECTIVE_FUNCTION=  PRESSURE_DROP
**OPTIMIZER= BFGS**
output for history_project.dat:
"PRESSURE_DROP"
 10791.40653
 10943.29967
 10943.29967
 11041.58637
 11041.58637

The PRESSURE_DROP was supposed to be reduced (weight -1) but it's increasing.

**With SLSQP I get:**
Sequential Least SQuares Programming (SLSQP) parameters:
Number of design variables: 56 ( 56 )
Objective function scaling factor: [1.0]
Maximum number of iterations: 20
Requested accuracy: 1e-20
.....
  NIT    FC           OBJFUN            GNORM
    1     1     1.078075E+00     6.354859E-11
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.07807522
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1

And no further designs are generated. What makes SLSQP to 'converge'?

**I am using branch** [turbo_output_opt](https://github.com/su2code/SU2/compare/develop...turbo_output_opt) (updated to latest develop).

Thanks in advance.

Config file: [case728.txt](https://github.com/su2code/SU2/files/4606913/case728.txt)

**Comment by pcarruscag** [comment]
In `CVolumetricMovement::SetBoundaryDisplacements` the periodic boundaries are left free, and so there is no guarantee that periodicity will be preserved.

I don't use the optimization framework, but the default formulation is usually to minimize, i.e. you use a negative weight if you want to maximize, have you tried not setting the weight to -1?

If you want to perturb a single parameter you change one of the values in DV_VALUE.

Attach your config...

**Comment by auzbaig** [comment]
I have used both weight +1 and -1 but the optimization direction appears to be independent of it. Another issue is that the OBJECTIVE_WEIGHT parameter is not printed correctly in the configs generated during optimization. Its always +1.

Is the DV_VALUE the same as "FINDIFF_STEP"? Or does its value happens to be the same?

And why is the DV_VALUE always the same during the optimization to 0.001? Shouldn't this depend on the case itself?

I have attached my config.

**Comment by clarkpede** [comment]
Regarding periodic boundaries: You have two options.  You can hack the code to not allow grid deformation on periodic boundaries.  That's a simple code edit, since the code already prevents most boundaries from being deformed.  Let me know if you want to use this option, and I can point you to those lines. Second, you can use the `HOLD_GRID_FIXED` and `HOLD_GRID_FIXED_COORD` options to prevent grid deformation outside a specific box.  I have found this option to be better overall, since it also makes the linear system easier to solve in `SU2_DEF`.

The `DV_VALUE` and `FINDIFF_STEP` are different. I've only seen `FINDIFF_STEP` used for the finite-differencing python script, though it may have other uses I am not aware of.

The `DV_VALUE` depends on the context.  When using `SU2_DOT`, `DV_VALUE` is set to its default value.  But when performing shape optimization using SU2's framework, the `DV_VALUE` parameters will be set based on the output of SLSQP (or whatever optimization framework you're using).

**Comment by pcarruscag** [comment]
DV_VALUE is set to the finite difference step when evaluating gradients in SU2_GEO idk if the same is done for the non-AD mode of SU2_DEF

**Comment by auzbaig** [comment]
@clarkpede I think it is simpler to lock the periodic boundaries. I can look into that if you can point me to it.

I have been using BFGS but the DV_VALUE is always 0.001 in the config_DOT_AD files, even after 25 design iterations.

**Comment by auzbaig** [comment]
I don't have any geometric constraints (or definitions) hence SU2_GEO is not being called. You can look at the config file.

**Comment by clarkpede** [comment]
To keep periodic boundaries from changing during mesh deformation:

I'm basing my description on the `develop` branch.  But the core code hasn't changed since at least v6.0.0, so you should be able to make the changes on your own branch.

During initialization, the DOF for grid points on boundaries are removed for everything **but**  symmetry, MPI, internal, and periodic BCs.  You just need to remove `PERIODIC_BOUNDARY` from the exceptions.  Here's the relevant lines:

https://github.com/su2code/SU2/blob/7c783a5e4ff41acebfc0e1327023809274fc1692/Common/src/grid_movement_structure.cpp#L1638

There's also a similar line for aeroelasticity problems.  You can find it by searching for `PERIODIC_BOUNDARY` in `Common/src/grid_movement_structure.cpp`.

If I remember correctly, changing that one line is sufficient to prevent the periodic boundaries from changing during mesh deformation.  Let me know if that doesn't work for you.

**Comment by auzbaig** [comment]
@clarkpede it works. The periodicity is being maintained. I am wondering why they were included there in the first place? Should we not make periodic boundaries fix in the main code?

**Comment by clarkpede** [comment]
I honestly don't know.  Maybe @economon or @jayantmukho might know? Why does the volume mesh deformation (currently) allow the periodic boundaries to deform?

**Comment by jayantmukho** [comment]
I am not sure about why periodic boundaries are allowed to deform. It doesn't seem to be a good idea unless there is a way to deform its periodic pair in the same way.

As for @auzbaig's question about why SLSQP converges in one step: There is a huge difference in the magnitude of the objective function, O(1) and the gradient O(-11). I am guessing the optimizer doesn't think it can reduce the function value any further since the gradient with respect to the DVs is so small. 

To change the relative magnitudes of the objective and gradient, you need to change the DV scaling. This isn't intuitive and is one of the things we are hoping to address in #922 . Check out the `obj_df` function in `SU2_PY/SU2/eval/design.py` (line 386 in the develop branch). There you see how the gradient is scaled: 

`grad[k] = grad[k] * sign * scale * global_factor / dv_scl` 

Here `scale` is the objective function scaling factor, `global_factor` is what you specify for the `OPT_GRADIENT_FACTOR`, the `dv_scl` is the design variable scaling. 

So if you wanted to bring the gradient norm to O(1), you'd have to specify a DV scaling of 1e-11. Usually a gradient norm of O(-6) is what seems to work best with SLSQP.

**Comment by economon** [comment]
> I honestly don't know. Maybe @economon or @jayantmukho might know? Why does the volume mesh deformation (currently) allow the periodic boundaries to deform?

I think it is best to freeze the periodic BCs. That line might be a hold over from the old definition of periodic BCs that used halo cells (can't quite remember why we froze them that way though), but now, we should remove that line. Please submit a PR if you have a min
