### ISSUE TITLE
Steady restarts should continue the iteration count rather than restarting from 0

### ISSUE THREAD

**Issue by economon** [su2code/SU2#99]

**Comment by taalf** [comment]
I agree with that :)

**Comment by fpalacios** [comment]
I can try to migrate this capability from the version of SU2 that I'm using.

**Comment by btracey** [comment]
It's not always the case that using a restart file is continuing from a simulation. For example, if one has a simulation that has a similar solution as a seed. An example would be doing optimization and using a nearby flow solution. Here, having the iteration count start from zero is useful, because it's the more accurate measure.

We would also have to this about how this interfaces with MAX_ITER. Right now it's really clear, but which does it mean when iterations don't start from zero?

**Comment by hlkline** [comment]
That's a good point. Maybe this functionality would be better as an optional config flag rather than the default behavior.
Alternatively, there could be a post-processing script to concatenate history files given a set of files and information about what the restart-writing frequency was.

**Comment by taalf** [comment]
Hello,
As a simple user, when I forget to save the last history before continuing a simulation I am very frustrated, because it is lost forever... Since the new history file erases the previous one.
Also, making these history backups is not very practical...
I would very prefer an option in the config file like: "when RESTART_SOL= YES append to the history or not?".
I think it would not be difficult to set another variable like: "max_it must be counted from the beginning or from the last launch?".
I agree it makes it a bit more complex, but not too much I think :)

**Comment by hlkline** [comment]
Maybe we could try to implement a check for whether the file exists in the directory and make a standard alteration to the name. We would have to be careful though that this doesn't interfere with cases that depend on the output files - aka continuous_adjoint, finite_difference, etc.

**Comment by btracey** [comment]
What do you mean? Right now there is no difference between the file that the solution is started from and saving of the current state. The "Restart" file is used to start the flow solution, and is then overwritten at each save. With the way the code is currently designed, it's impossible to tell if the restart file is just intended to provide the initial flow state, or if the file is really a restart.

**Comment by taalf** [comment]
Hello,
In another similar CFD code (Edge), the "restart" option is not "yes" or "no", but "0", "1", "2", meaning respectively: "from scratch" , "from initialization file (iterations from scratch)", "continuing iterations from the last solution".

**Comment by hlkline** [comment]
If we go that direction we could use the ENUM options structure that already exits for other settings, allowing the user to set this with a word rather than a number (maybe NO, YES, and APPEND_HISTORY so that current config files would still work the same way, where "YES" means the same as "from initialization file")

**Comment by talbring** [comment]
The iteration number is now stored in the restart files so we should definitely have this feature. Because at the moment it is not clear when the iteration stops (because EXT_ITER is still counted from 0).

**Comment by hlkline** [comment]
This appears to be the current behavior - closing
